### ISSUE TITLE
Que URL se le indica a Mercadopago en "Quiero ir a Producción" en un esquema con LoadBalancer.

### ISSUE THREAD

**Issue by christiansalazar** [mercadopago/dx-php#101]
Estimados.

En nuestra arquitectura tenemos un Loadbalancer para la URL de compras, digamos que "http://compras.chileshift.cl" es la URL que apunta al LoadBalancer de compras. Como consecuencia "uno de los multiples servidores de compra" iniciará la conversación con mercadopago, por tanto mi pregunta es: 

que URL debo darle a Mercadopago en el [formulario "quiero ir a producción"](https://www.mercadopago.com/mla/account/credentials), pienso que debería yo poner la URL del loadbalancer. Mi duda es que cuando el loadbalancer delegue el servicio a "compras1.chileshift.cl" entonces los pagos (y/o la conexión) sean reachazados porque no es la misma del loadbalancer.

**Comment by joelibaceta** [comment]
@christiansalazar para el formulario de homologación debes proveer alguna url donde se pueda encontrar tu aplicación para validar los requisitos de puesta en producción.
