### ISSUE TITLE
MercadoPago/Entity.php echo error

### ISSUE THREAD

**Issue by nicoandrade** [mercadopago/dx-php#102]
**Describe the bug**
Hay unos "echo" dentro de 
https://github.com/mercadopago/dx-php/blob/aefc1e36be3ab1ed520e5578f363cfbd09baf29b/src/MercadoPago/Entity.php#L152
https://github.com/mercadopago/dx-php/blob/aefc1e36be3ab1ed520e5578f363cfbd09baf29b/src/MercadoPago/Entity.php#L157
https://github.com/mercadopago/dx-php/blob/aefc1e36be3ab1ed520e5578f363cfbd09baf29b/src/MercadoPago/Entity.php#L161

Al hacer un update responde con unos "echo".
Imagino que habra sido algo para testing y quedo en producción.

**Comment by joelibaceta** [comment]
@nicoandrade disculpa el error, ahi estoy subiendo el fix.
