### ISSUE TITLE
Al Crear un pago no devuelve la respuesta del servidor

### ISSUE THREAD

**Issue by nicoandrade** [mercadopago/dx-php#103]
**Describe the bug**
Con las ultimas versiones del SDK, al momento de guardar un pago:
```
...
$response = $payment->save();
````
En caso de error, devuelve el mismo objeto Payment vacío. Sin ningún tipo de información acerca del error que haya sucedido.

En una version anterior que tengo en mi servidor, la variable `$response` obtenía la respuesta del servidor, ejemplo:
```
Array
(
    [code] => 201
    [body] => Array
        (
            [id] => 16894791
            [date_created] => 2018-12-01T03:22:09.000-04:00
            [date_approved] => 2018-12-01T03:22:09.000-04:00
            [date_last_updated] => 2018-12-01T03:22:09.000-04:00
            [date_of_expiration] => 
            [money_release_date] => 2018-12-15T03:22:09.000-04:00
            [operation_type] => regular_payment
            [issuer_id] => 3
            [payment_method_id] => master
            [payment_type_id] => credit_card
            [status] => approved
            [status_detail] => accredited
            [currency_id] => ARS
            [description] => Captura de prueba
...
```
Como se puede hacer para volver a tener esta funcionalidad en las versiones mas recientes del SDK?

Sino no hay forma de saber que tipo de errores suceden. Actualmente, en caso de error al querer crear un payment, lo único que recibimos es el objeto Payment vacío.

Otra cosa, hay forma de saber que versión exacta del SDK? Porque en este archivo siempre es la misma version:
https://github.com/mercadopago/dx-php/blob/27bdd4b20c228a068d53eaace6b4b118b89a9720/src/MercadoPago/Version.php#L6

**To Reproduce**
Simplemente hacer un pago con SDK 1.2

Gracias.

**Comment by nicoandrade** [comment]
Sumo un ejemplo de como recibo la variable `$response`en la version vieja que tengo del SDK, en caso de error al guardar un pago:
```
Array
(
    [code] => 400
    [body] => Array
        (
            [message] => token attribute can't be null
            [error] => bad_request
            [status] => 400
            [cause] => Array
                (
                    [0] => Array
                        (
                            [code] => 4000
                            [description] => token attribute can't be null
                            [data] => 
                        )

                )

        )

)
```
Sería ideal que esto vuelva a pasar en las nuevas versiones, porque de esta forma se sabe exactamente cual fue el error al guardar un pago.

No se que version es porque no se como fijarme en el código como explique antes siempre figura la misma version.

**Comment by joelibaceta** [comment]
@nicoandrade estamos trabajando en una forma estándar de comunicar los errores en los SDKs.

**Comment by nicoandrade** [comment]
Que bueno escuchar eso.
Hay algo que se puede ir viendo como para tener un idea de que forma manejarlos?
Así cualquier cosa que haga se vaya preparando a esa funcionalidad.

Gracias!

**Comment by joelibaceta** [comment]
@nicoandrade  con el ultimo merge https://github.com/mercadopago/dx-php/pull/137/files disponibilizamos un atributo que contiene el detalle del error y el retorno de un booleano al usar un método save() o update() para validar si se pudo procesar correctamente la sintaxis es:

   if ($payment->save()) {
      echo $payment->status;
    } else {
      echo "Error detail: " . $payment->error;
    }
En breve deberíamos disponibilizar una nueva version que incluya este feature
