### ISSUE TITLE
Erro en el nombre de la clase Invoice

### ISSUE THREAD

**Issue by nicoandrade** [mercadopago/dx-php#104]
Hay un typo en en el nombre de la clase Invoice:
https://github.com/mercadopago/dx-php/blob/aefc1e36be3ab1ed520e5578f363cfbd09baf29b/src/MercadoPago/Entities/Invoices.php#L13

**Comment by joelibaceta** [comment]
Gracias por el reporte, lo trataremos de corregir durante el día.

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-php/commit/6efe2ab88a5efda7e29ed63557997e03dbed7119
