### ISSUE TITLE
Error de creación de pago

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#105]
A veces la creación del pago falla y no encontré la manera de recuperar el porqué. Algun metodo para obtener la razón?

Por ejemplo un payment de suscripción puede fallar porque la tarjeta de crédito venció. Hoy en día tengo que ir en debug en el código para poder obtener esta información.

Muchas gracias!

**Comment by joelibaceta** [comment]
@nitescent Estamos trabajando en una forma genérica cross-sdk de devolver los errores del API.

**Comment by nitescent** [comment]
Gracias @joelibaceta, tienen una fecha estimada de disponibilidad?

**Comment by joelibaceta** [comment]
@nitescent con el ultimo merge https://github.com/mercadopago/dx-php/pull/137/files disponibilizamos un atributo que contiene el detalle del error y el retorno de un booleano al usar un método save() o update() para validar si se pudo procesar correctamente la sintaxis es:

```
   if ($payment->save()) {
      echo $payment->status;
    } else {
      echo "Error detail: " . $payment->error;
    }
```

En breve deberíamos disponibilizar una nueva version que incluya este feature

**Comment by nitescent** [comment]
Ok! Como puedo estar al tanto de que está disponible?

**Comment by joelibaceta** [comment]
Cada version nueva se refleja en la sección [releases](https://github.com/mercadopago/dx-php/releases)

**Comment by nitescent** [comment]
Gracias.
