### ISSUE TITLE
Conflicto de dependencias

### ISSUE THREAD

**Issue by lsfiege** [mercadopago/dx-php#106]
**Describe the bug**
Entiendo que no es directamente un bug de este sdk, pero existe un conflicto de dependencias al querer implementarlo en una app que hace uso del componente doctrine/dbal ^2.8 y por otro lado, este componente usa componentes de doctrine/common 2.6 y doctrine/annotations 1.4.

**To Reproduce**
Si se usa la versión 1.2 funciona perfecto y no arroja problemas de instalación, por lo que este error aparece luego de los ultimos cambios adicionados.

**Screenshots**
![image](https://user-images.githubusercontent.com/13440507/49372845-bd0f4c80-f6da-11e8-836c-2503788e3cf1.png)

**Comment by enzonotario** [comment]
También tengo este problema... ¿hay alguna intención de actualizar las dependencias?

**Comment by lsfiege** [comment]
En mi caso solo removí la dependencia de doctrine dentro del archivo `composer.json` de laravel, ya que no lo necesitaba ni yo, ni el framework: [link](https://github.com/laravel/laravel/blob/master/composer.json)

**Comment by enzonotario** [comment]
mm pero yo si lo necesito...

**Comment by fgilio** [comment]
IDEM, también necesito esa dep. @joelibaceta podrán actualizar estas dep?

**Comment by joelibaceta** [comment]
@fgilio usamos estas versiones para mantener compatibilidad con PHP < 7.x, ya que a partir de la versión 1.5 de doctrine/annotations se pierde el soporte para PHP 5.x.

**Comment by bachilli** [comment]
https://github.com/mercadopago/dx-php/pull/132

**Comment by francuello** [comment]
Buenas tardes, en mi caso trabajo con ZF (algunos proyectos en la 2 y otros en la 3) y no puedo solucionarlo. Por el momento estoy dándome vueltas con CuentaDigital.com, pero quiero irme a MP.
Que solución pueden darme?
