### ISSUE TITLE
Call to undefined method MercadoPago\Payment::refund()

### ISSUE THREAD

**Issue by juampi92** [mercadopago/dx-php#107]
**Describe the bug**
I can't do `$payment->refund();` because it seems that it's not yet implemented.

**To Reproduce**
1. Use the example on 
https://www.mercadopago.com.ar/developers/es/guides/manage-account/cancellations-and-refunds
```php
<?php

$payment = MercadoPago\Payment::find_by_id($payment_id);
$payment->refund();

?>
```
2. See error
```Call to undefined method MercadoPago\Payment::refund();```

**Expected behavior**
The payment was refunded.

**Error**

```
Call to undefined method MercadoPago\Payment::refund();
```

**Server (please complete the following information):**
 - PHP 7.0.15

**Comment by joelibaceta** [comment]
@juampi92 which SDK version are you using?

**Comment by juampi92** [comment]
From composer.lock

```json
"name": "mercadopago/dx-php",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/mercadopago/dx-php.git",
                "reference": "c394b32e6702a02ef8b100862a4702234ccce019"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/mercadopago/dx-php/zipball/c394b32e6702a02ef8b100862a4702234ccce019",
                "reference": "c394b32e6702a02ef8b100862a4702234ccce019",
                "shasum": ""
            },
```

**Comment by juampi92** [comment]
It's been two weeks, so I ended up using directly the API without the SDK, but thanks for the response.

Perhaps you might want to update the documentation as well.

**Comment by andreud** [comment]
Whats currently on the documentation guides doesnt work (as @juampi92 noted ),
Please update documentation guides to note this.

**Comment by mateo2181** [comment]
any solution for this? I have same problem.

**Comment by juampi92** [comment]
> @juampi92 did you try using Refund Class?
> 
> ```
> $refund = new MercadoPago\Refund();
> $refund->payment_id = $id;
> $refund->save();
> ```

This doesn't work? @mateo2181

**Comment by mateo2181** [comment]
I am doing this:
`
  public function refundOrder($orderId)
      {
        try {
        
            MercadoPago\SDK::setAccessToken(env('MP_TOKEN_PROD'));
            $orderMP = $this->orderMPRepository->getByOrderId($orderId);
            $merchant_order = MercadoPago\MerchantOrder::find_by_id($orderMP->merchant_order_id);

            if(count($merchant_order->payments) > 0) {
                foreach ($merchant_order->payments as $payment) {   
                    $p = MercadoPago\Payment::find_by_id($payment->id);
                    $refund = new MercadoPago\Refund();
                    $refund->amount   = $p->total_paid_amount;
                    $refund->metadata = "A total refund";
                    $refund->save();

                }
            }

            if(!$merchant_order) {
                return false;
            }
            dd($merchant_order);
        } catch (Exception $e) {
            echo $e;
            exit;
        }
    }`

find_by_id is working. But I get this error:
![Screenshot (2)](https://user-images.githubusercontent.com/12451246/55627717-41570680-5785-11e9-8e49-0d108bfa29be.png)

**Comment by mateo2181** [comment]
When I comment foreach I get the merchantOrder correctly. But if I do https://api.mercadopago.com/v1/merchant_orders/1100030702?access_token=[ACCESS_TOKEN]  from Postman I get { "status": 404, "message": "Not Found" }

**Comment by mateo2181** [comment]
I am working with test users, and I tried to do it with ACCES_TOKEN of sandbox and production.

**Comment by mateo2181** [comment]
> > @juampi92 did you try using Refund Class?
> > ```
> > $refund = new MercadoPago\Refund();
> > $refund->payment_id = $id;
> > $refund->save();
> > ```
> 
> This doesn't work? @mateo2181

This seems to work but when I get payment the field amount_refunded=0 and status="approved"

**Comment by juampi92** [comment]
That code doesn't have this line `$refund->payment_id =  $p->id;`

**Comment by mateo2181** [comment]
`
$merchant_order = MercadoPago\MerchantOrder::find_by_id($orderMP->merchant_order_id);

            if(count($merchant_order->payments) > 0) {
                foreach ($merchant_order->payments as $payment) {   
                    $p = MercadoPago\Payment::find_by_id($payment->id);
                    $refund = new MercadoPago\Refund();
                    $refund->metadata = "A total refund";
                    $refund->amount   = $p->total_paid_amount;
                    $refund->payment_id = $payment->id;
                    $refund->save();
                }
            }`

This wil be fine, right? 
I have tried it, but amount_refunded=0.

**Comment by phgoncalves** [comment]
@juampi92 
The method refund was added in the version 1.4.0 .
With this method is posible to make complete refunds.
`$payment->refund()`

And partial refunds.
`$payment->refund($amount_refunded)`
