### ISSUE TITLE
Error: the attribute payer.type is not a possible param

### ISSUE THREAD

**Issue by SebastianCBA** [mercadopago/dx-php#112]
Hola! Lo siguiente:

`        $filters = array (
            "id" => "approved",
            "operation_type" => "regular_payment",
            "payer.email" => "customer",            
        );                

        $pagos_recibidos = $mp->search_payment($filters, 0, 10);`

Me devuelve el siguiente error:

the attribute payer.email is not a possible param

Alguien sabe que puede suceder?

**Comment by joelibaceta** [comment]
@SebastianCBA es correcto, el email no es un parámetro de búsqueda, el filtro de usuarios se hace a partir del id del payer `payer_id`
