### ISSUE TITLE
Call to undefined method MercadoPago\RestClient::deleted()

### ISSUE THREAD

**Issue by informaticosgb** [mercadopago/dx-php#116]
Hola, quiero borrar un pago y me sale el error **Call to undefined method MercadoPago\RestClient::deleted()** 

El código en SDK.php es 

```
public static function delete($uri, $options=[])
 {
      if ($token = self::$_config->get('ACCESS_TOKEN')) {
        $uri = $uri . "?access_token=" . $token;
      }
      return self::$_restClient->deleted($uri, $options);
 }
```

En la línea 147 debería ser return self::$_restClient->**delete**($uri, $options);

Cuando cambio "**deleted**" por "**delete**" me sale éste error 

```
array:2 [▼
  "code" => 405
  "body" => null
]
```
En mi controlador tengo éste código: 

```
use MercadoPago\SDK;

....

$deleted = SDK::delete("/v1/payments/4368913390");
dd($deleted);
```

Espero su pronta ayuda, gracias !

**Comment by joelibaceta** [comment]
@informaticosgb no es posible "borrar" un pago, solo devolverlo y cancelarlo, según su estado.
