### ISSUE TITLE
Call to undefined method MercadoPago\Payment::delete()

### ISSUE THREAD

**Issue by informaticosgb** [mercadopago/dx-php#117]
No se encuentra el método delete() cuando hago 

```
use MercadoPago\SDK;

...

$payment = Payment::find_by_id('4368913390');
$payment->delete();
```

Espero de su ayuda, gracias !

**Comment by joelibaceta** [comment]
@informaticosgb es correcto no se puede "eliminar" un pago, solo cancelarlo o devolverlo.
