### ISSUE TITLE
Estaria bueno mostrar proceso de instalación como video

### ISSUE THREAD

**Issue by pabal1708** [mercadopago/dx-php#122]
Hoy existen herramientas que nos permiten grabar una sesión de terminal como https://github.com/nbedos/termtosvg y quizas esto haga mas intuitivo el proceso de instalación para quien este interactuando pro primera vez con el sdk y/o composer

**Comment by joelibaceta** [comment]
Something like this? https://gist.github.com/joelibaceta/8edf594bb27fd3f8296827c68c24357a
