### ISSUE TITLE
"Preapprovals are not available for this country yet"

### ISSUE THREAD

**Issue by fgilio** [mercadopago/dx-php#124]
Hola!

Esto es más bien una consulta.
Tenemos clientes que están recibiendo errores al crear Preapprovals porque aparentemente estos no están disponibles en su país.
El problema es que nuestro sistema se entera no por una excepción levantada en el SDK, sino porque el objeto Preapproval tiene un `init_point=null`.
Por lo que veo [acá en la clase Entity](https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Entity.php#L235-#L237) solo se tiene en cuenta el caso en que la operación es satisfactoria y se ignoran los que, por ej, dan un 400 con el mensaje "Preapprovals are not available for this country yet".

Cómo podemos manejar estos casos? Alguna recomendación?

Slds

**Comment by joelibaceta** [comment]
Te recomiendo revisar la sección de manejo de errores, https://github.com/mercadopago/dx-php/wiki/Error-Handling.

**Comment by fgilio** [comment]
thx
