### ISSUE TITLE
The body must be a Json Object

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#127]
**Describe the bug**
Versión "mercadopago/dx-php": "^1.0.0"
Cuando cambio la default card de un customer, funciona, pero mp devuelve "the body must be a Json Object".

**To Reproduce**
```
$customer = Customer::find_by_id($customer_id);
$customer->default_card = $card_id;
$customer->update();
```

Response MercadoPago
status 400
code 118
description the body must be a Json Object

Hago un GET del Customer, veo que la operación ha funcionado.

**Comment by joelibaceta** [comment]
@nitescent ¿podrías comentarnos si con las versiones más recientes del SDK pudiste resolverlo?

**Comment by nitescent** [comment]
@joelibaceta no sería más coherente que ustedes hagan las pruebas y nos avisen cuando está testeado, funcionando y incluido en la nueva release?

Sino nosotros estamos perdiendo tiempo. Recién use la nueva release del SDK y tiene bugs. Hice un attach de card, falló por no sé cual razón, y si entiendo bien el código que debería mostrarme la razón tiene fallas:

`[2019-03-12 19:35:54] production.DEBUG: MercadoPagoService::attachCard {"exception_type":"Exception","Exception":"[object] (ErrorException(code: 0): Illegal string offset 'code' at /var/www/bambox-api/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php:283)`

**Comment by nitescent** [comment]
@joelibaceta no sería más coherente que ustedes hagan las pruebas y nos avisen cuando está testeado, funcionando y incluido en la nueva release?

Sino nosotros estamos perdiendo tiempo. Recién use la nueva release del SDK y tiene bugs. Hice un attach de card, falló por no sé cual razón, y si entiendo bien el código que debería mostrarme la razón tiene fallas:

`[2019-03-12 19:35:54] production.DEBUG: MercadoPagoService::attachCard {"exception_type":"Exception","Exception":"[object] (ErrorException(code: 0): Illegal string offset 'code' at /var/www/xxxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php:283)`

**Comment by nitescent** [comment]
@joelibaceta 

`
(1/1) ErrorClass 'MercadoPago\MercadoPago\ErrorCause' not found
--
in RecuperableError.php line 20
`

![image](https://user-images.githubusercontent.com/4238385/54307414-67382380-45aa-11e9-9c1e-7707aca9502a.png)

**Comment by joelibaceta** [comment]
@nitescent hola, el comentario tenia cómo intención validar si este era un bug histórico aun no resuelto debido al tiempo transcurrido desde su creación o había sido resuelto en una de las versiones posteriores a la 1.0.0.

**Comment by nitescent** [comment]
Hola @joelibaceta pudieron resolver el problema de class not found?
Impide usar la posibilidad de recuperar las causas de errores.
Gracias

**Comment by joelibaceta** [comment]
Si, fue liberada la version 1.2.6 que contiene el feature de error-handling funcional

**Comment by nitescent** [comment]
> @nitescent ¿podrías comentarnos si con las versiones más recientes del SDK pudiste resolverlo?

Hola @joelibaceta este error "The body must be a Json Object" sigue. Pueden resolverlo?

**Comment by nitescent** [comment]
@joelibaceta Este problema lo podés solucionar?
Perdón que abrí varios issues, no dudes en cerrar los duplicados.

**Comment by nitescent** [comment]
@joelibaceta 
Este problema es el mismo que https://github.com/mercadopago/dx-php/issues/131
Si querés cerrar uno de los dos.
Tenés alguna novedad de corrección de este bug?

**Comment by phgoncalves** [comment]
@nitescent 
Hicimos algunos cambios en el update del SDK. Probamos este escenario en las versión 1.5.0 sin problemas.
