### ISSUE TITLE
Call to undefined method MercadoPago\Customer::id() 

### ISSUE THREAD

**Issue by DesandaBaAs** [mercadopago/dx-php#129]
Hola! Estoy recibiendo un error al tratar de generar un usuario y asociarlo a una tarjeta (modo sandbox). 

Call to undefined method MercadoPago\Customer::id() 

Aquí está el script

```
<?php
require_once 'vendor/autoload.php';

    MercadoPago\SDK::setAccessToken("TEST-..."); //aquí tengo configurado el token
    

    $customer = new MercadoPago\Customer();
    $customer->email = "test_payer_196537287@testuser.com";
    $customer->save();
    
   $card = new MercadoPago\Card();
    $card->token = "ade8..."; //aquí tengo configurado el token que recibí al capturar los datos de la tarjeta
    $card->customer_id = $customer->id();
    $card->save();   
?>
```

**Comment by wallacemaxters** [comment]
aparentemente, para obtener el valor de la variable, es necesário utilizar la propriedad `id`.

**Comment by i5o** [comment]
Buenas, tuve el mismo error y intente hacer lo que @wallacemaxters comentó.
Pero cuando hago un var_dump de customer, me da que ID es null; acaso el metodo `$customer->save();` no está funcionando?

**Comment by AlanAlc** [comment]
Para todas las propiedades del objeto solo retira el par de () final. En este caso:

$card->customer_id = $customer->id(); reemplazalo por $card->customer_id = $customer->id;
