### ISSUE TITLE
Error 500 al hacer pause de una Subscription

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#130]
SDK "mercadopago/dx-php": "^1.0.0"

Esto es la manera correcta para pausar una subscription?

```php
use MercadoPago\Subscription;

$subscription = Subscription::find_by_id($id);
$subscription->status = 'paused';
$subscription->update();
```

La línea 3 tira un error 500:

```javascript
{"message":"Oops! Something went wrong...","error":"internal_error","status":500,"cause":[]}
```

**Comment by joelibaceta** [comment]
@nitescent by now we are not supporting subscriptions through SDK because we are working in a new API design for this product.

**Comment by nitescent** [comment]
Ok so what is the recommended way to manage subscriptions?
