### ISSUE TITLE
Error 400 al actualizar la default Card de un Customer

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#131]
**Describe the bug**

Versión SDK "mercadopago/dx-php": "^1.0.0"

Esto es la manera correcta para hacer update de la default card?

**To Reproduce**

```php
use MercadoPago\Customer;

$customer = Customer::find_by_id($id);
$customer->default_card = $card_id;
$customer->update();
```

La línea 3 tira un error 400:

```javascript
{"message":"invalid parameters ","error":"bad_request","status":400,"cause":[{"code":"118","description":"the body must be a Json Object"}]}
```

**Comment by joelibaceta** [comment]
@nitescent ¿Podrías comentarnos si con las ultimas versiones del SDK aun tenes este problema?

**Comment by nitescent** [comment]
Hola @joelibaceta , lo tiene aún :/
Por favor si lo podés resolver 🙏

**Comment by nitescent** [comment]
Hola @joelibaceta 
Alguna novedad?

**Comment by phgoncalves** [comment]
@nitescent
Hicimos algunos cambios en el update del SDK. Probamos este escenario en las versión 1.5.0 sin problemas.
