### ISSUE TITLE
Confusión a respecto de la documentacíon del Marketplace

### ISSUE THREAD

**Issue by wallacemaxters** [mercadopago/dx-php#138]
Yo estoy leyendo la documentación del Marketplace y estoy confuso a respecto de la comisión del vendedor.

En este ejemplo, hay una propiedad llamada "user token", pero no hay esa propiedad en el SDK
```
<?php  

  require ('mercadopago.php');
  MercadoPago\SDK::configure(['ACCESS_TOKEN' => 'TEST-1361656468033953-022522-6808be1d1493adf08b3ede7c43950cee-406841956']);

  $payment = new MercadoPago\Payment();

  $payment->transaction_amount = 100;
  $payment->token = "ff8080814c11e237014c1ff593b57b4d";
  $payment->description = "Title of what you are paying for";
  $payment->installments = 1;
  $payment->payment_method_id = "visa";
  $payment->user_token = "ENV_USER_TOKEN";
  $payment->payer = array(
    "email" => "test_user_19653727@testuser.com"
  );

  $payment->save();

?>
```

Cómo hago para definir el usuario que recibirá el pago? 

https://www.mercadopago.com.br/developers/en/guides/marketplace/api/create-marketplace/

**Comment by AlanAlc** [comment]
Por lo que entiendo el usuario que recibe el pago es a quien corresponde el ACCESS_TOKEN pues efectivamente no existe $payment->user_token sin embargo la documentación no especifica de forma clara  que así sea. En la sección **3. Integra la API para recibir pagos** dice:
_Para recibir pagos en nombre de tus vendedores debes integrar la API, utilizando el **access_token** de cada vendedor para tu aplicación._ En mi caso lo hago así y el flujo no tiene errores. El problema que yo estoy experimentando es que al hacer el flujo:  

`$payment->save();` 
`var_dump($payment->status);`
`var_dump($payment->id);`

siempre obtengo:

`["status":protected]=> NULL]`
`["id":protected]=> NULL]`

No se si se deba a que estoy usando tarjetas de prueba. Avisame si logras hacer correctamente el pago y si puedes obtener el id o status del pago.

**Comment by wallacemaxters** [comment]
Alan, cuando el id del pago en SDK es NULL, es problable que tenga ocurrido un error 400.


Tú puedes los buscar en el arquivo de log del Apache o PHP.

El SDK utiliza `error_log` para guardar los errors.

(yo soy de Brasil. Lo siento se escribo malo)

**Comment by AlanAlc** [comment]
Te lo agradezco Wallace! Me fue de mucha ayuda tu comentario ya logré realizar el pago con éxito.

**Comment by emleonardelli** [comment]
Yo estoy con el mismo problema y el log me da error de que el nombre del atributo "user_token"  es incorrecto

Reviso la clase payment y efectivamente no tiene el atributo $user_token

Como lograron efectuaron hacer el cobro?
