### ISSUE TITLE
Create preference Payer Info doesn't match attributes

### ISSUE THREAD

**Issue by bachilli** [mercadopago/dx-php#142]
When creating a preference, if I want to attach Payer info, the attributes doesn't match with the docs:

https://www.mercadopago.com.ar/developers/pt/guides/payments/web-checkout/receive-payments/

in the docs we have name and surname, in the Payer entity we do have first_name and last_name.

Whos correct?

**Comment by joelibaceta** [comment]
@bachilli the correct attributes are `name` and `surname`, we are going to correct this, thanks for reporting.

**Comment by bachilli** [comment]
@joelibaceta There's something wrong... When I was creating a preference the attributes are name and surname, but in the return (response of the API), I receive first_name and last_name.

**Comment by joelibaceta** [comment]
@bachilli Payments API use `first_name` and `last_name` but Preferences API use `name` and `surname`, is its true, but this will not change in the short term. 
Unfortunately we will have to write another Payer structure in the SDK.

**Comment by joelibaceta** [comment]
Temporally solved with https://github.com/mercadopago/dx-php/commit/da22247417951a27ea74c2c02c7dea2f185b65aa we are going to solve this better in the future.
