### ISSUE TITLE
method refund() in Payment doesnt work

### ISSUE THREAD

**Issue by bachilli** [mercadopago/dx-php#143]
Reference: https://www.mercadopago.com.br/developers/pt/guides/manage-account/cancellations-and-refunds/

**Comment by danielcastro02** [comment]
Tenho o mesmo problema, existe algum outro meio de fazer as devoluções?

**Comment by phgoncalves** [comment]
@bachilli @danielcastro02 
This issue was fixed in the version 1.4.0.
