### ISSUE TITLE
Class 'MercadoPago\MercadoPago\ErrorCause' not found

### ISSUE THREAD

**Issue by faguiargptools** [mercadopago/dx-php#144]
I'm getting an error when I using it in Laravel 5.8, PHP 7.1.

![image](https://user-images.githubusercontent.com/9253467/54357052-e1fd4f00-463b-11e9-8b39-6f849d144c90.png)

**Comment by joelibaceta** [comment]
We solved this yesterday https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Generic/RecuperableError.php#L20

**Comment by faguiargptools** [comment]
Thank you so much
