### ISSUE TITLE
Opciones de Envío

### ISSUE THREAD

**Issue by plencovich** [mercadopago/dx-php#150]
Tengo integrado Mercadopago en varios sitios webs, a la hora de integrar Mercado Envíos me encontré con el problema de que no aparecen todas las opciones (Retiro en sucursal del Correo, Envio a domicilio, etc) sólo aparecen como opción recomendada "Normal a Domicilio"

```
[display] => recommended
[cost] => 284,99
[shipping_method_id] => 73328 
.....
[id] => 391942242
[shipping_method_type] => standard
[name] => Normal a domicilio
```

He visto en otras tiendas que muestran las opciones como en Mercadolibre que son las que se obtienen de este API: 

`curl -X GET https://api.mercadolibre.com/sites/MLA/shipping_options?zip_code_from=7200&zip_code_to=01310909&dimensions=16x16x16,1500`

El tema que yo si hago el cálculo con esa información, no puedo agregarlo a Mercado Pago con Mercado Envió incluido porque a la hora de realizar el web checkout me muestra siempre el Normal a domicilio por más que cambie el default_shipping_method.

Hay alguna solución para poder ofrecer en Mercadopago todo junto?

Gracias.

 Tema referente al PHP SDK [Mercado Envíos API - Habilitar todos los métodos/formas de envío? #114](https://github.com/mercadopago/sdk-php/issues/114)

**Comment by joelibaceta** [comment]
Este canal no esta destinado al soporte general sobre el funcionamiento de productos de MercadoPago, para soporte general sobre otros servicios, APIs o productos contactarse al canal de soporte tecnico oficial. http://mercadopago.com.ar/developers/es/support/

**Comment by gallagherbros** [comment]
Hola, @plencovich . consulta pudiste solucionar este tema? también me pasa lo mismo no encontré la forma. Gracias

**Comment by plencovich** [comment]
@gallagherbros hola, no, sólo pude hacer un cotizador, y despues ese valor que lanza el cotizador se lo agrego al valor de la compra. pero siempre sale con el envio normal a domicilio.

la otra que hay que hacer es usar la api de ML para todo y la parte de pago con mercadopago. pero no lo he probado.
