### ISSUE TITLE
Integration errors

### ISSUE THREAD

**Issue by joselaprida8** [mercadopago/dx-php#153]
**Primer error** es que en "**dx-php/samples/index.php**"  la siguiente linea da error:
**MercadoPago\MercadoPagoSdk::initialize();** 

Uncaught Error: **Class 'MercadoPago\MercadoPagoSdk' not found**

deberia ser **MercadoPago\SDK::initialize();** 

Corrigiendo eso al intentar inicializar MercadoPago obtengo el **siguiente error**:
Fatal error: Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned

**Comment by joselaprida8** [comment]
Fatal error: Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned

this error is returned when using subdomain.
for example in www.domain.com/mercadopago/index.php works fine, but mercadopago.domain.com will through that error even if both point to the same file.

**Comment by joselaprida8** [comment]
It works fine with PHP 7.1

**Comment by joelibaceta** [comment]
@joselaprida8 check your dependencies, we discus this on this thread https://github.com/mercadopago/dx-php/pull/136
