### ISSUE TITLE
Error Payment with Sandbox Credentials

### ISSUE THREAD

**Issue by mateo2181** [mercadopago/dx-php#154]
**Describe the bug**
Estoy probando la integración con web checkout siguiente la documentación de acá:
https://www.mercadopago.com.ar/developers/es/guides/payments/web-checkout/receive-payments/
Siempre recibo el mismo error de la imagen.
No estoy usando usuarios de prueba. Traté de generar usuarios de prueba pero me dice que ya alcanzé mi limite. Y no se como recuperar los que alguna vez generé, hay alguna forma de hacerlo?

Gracias

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/12451246/55343177-f6857800-5480-11e9-935a-dc51a3209b7c.png)

**Server (please complete the following information):**
 - Laravel 5.6
 - Php 7.1.3

**Comment by joelibaceta** [comment]
@mateo2181 este no es un canal de soporte general sobre productos o servicios de MercadoPago, sino esta destinado únicamente a la discusión sobre bugs o feature request de este SDK.

Te comparto el canal de soporte oficial https://www.mercadopago.com.ar/developers/es/support/
