### ISSUE TITLE
Web checkout rechaza tarjetas (high_risk) pero funciona con efectivo

### ISSUE THREAD

**Issue by faculezcano** [mercadopago/dx-php#156]
Estoy migrando de la sdk legacy y me pasa que el nuevo web checkout me rechaza todas las tarjetas pero funciona bien con efectivo, no es si es su scope ya que ustedes solo dan una interfaz para llegar al web checkout, pero esto no me pasa con el web checkout saliendo de la sdk vieja. Ademas MP no me rechaza las tarjetas de otros sitios que usan la pasarela por eso intuyo que la diferencia esta en esta sdk.

```php
$preference = new MercadoPago\Preference();
# Create an item object
$item = new MercadoPago\Item();
$item->id = $operationid;
$item->title = substr($oferta['titulo'],0,256);
$item->description = substr($oferta['subtitulo'],0,256);
$item->quantity = intval($cantidad);
$item->currency_id = "ARS";
$item->unit_price = floatval($precio_unitario);
$item->picture_url = "https://".$_SERVER['SERVER_NAME'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/images/ofertas/".$idoferta .'/'. $oferta['imagen_box'];
# Create a payer object
$payer = new MercadoPago\Payer();
$payer->name = $cliente['nombre'];
$payer->surname = $cliente['apellido'];
$payer->email = $cliente['email'];
/*$payer->identification = array(
	"type" => "DNI",
	"number" => $cliente['dni']
);*/
# Setting preference properties
$preference->items = array($item);
$preference->payer = $payer;

$preference->back_urls = array(
	"success" => "https://".$_SERVER['SERVER_NAME'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/exito-mp.php?operationid=".$operationid,
	"pending" => "https://".$_SERVER['SERVER_NAME'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/exito-mp.php?operationid=".$operationid,
	"failure" => "https://".$_SERVER['SERVER_NAME'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/error-mp.php?operationid=".$operationid
);
$preference->notification_url = "https://".$_SERVER['SERVER_NAME'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/callback-mp.php";
$preference->auto_return = "approved";

$preference->external_reference = $source;
$preference->binary_mode = false;

$preference->save();

header('Location: '.$preference->init_point);
```

Otro detalle, el ejemplo de IPN que muestran en la web tiene 2 errores, falta un ")" y un break; al primer case.

**Comment by faculezcano** [comment]
Estoy sospechando que no se envian los datos del payer ya que analizando el payment que MP me devuelve:
`"payer": {
    "email": null,
    "entity_type": null,
    "first_name": null,
    "id": "91849376",
    "identification": {
    },
    "last_name": null,
    "operator_id": null,
    "phone": {
    },
    "type": "guest"
  },`

pero el print_r del $preference que envio a MP me da esto:
`[payer:protected] => MercadoPago\Payer Object
        (
            [name:protected] => Facundo
            [surname:protected] => Lezcano
            [email:protected] => facu_lezca@hotmail.com
            [date_created:protected] => 
            [phone:protected] => stdClass Object
                (
                    [area_code] => 
                    [number] => 
                )

            [identification:protected] => stdClass Object
                (
                    [type] => 
                    [number] => 
                )

            [address:protected] => stdClass Object
                (
                    [street_name] => 
                    [street_number] => 
                    [zip_code] => 
                )

            [_last:protected] => 
        )`

**Comment by joelibaceta** [comment]
@faculezcano te comento, el payer asignado para la preferencia no necesariamente se ve reflejado en payment ya que puedes hacer un pago de forma anónima sin contar con una cuenta de MercadoPago para una preferencia o con un payer distinto, esto te lo indica el parámetro `"type": "guest"`.

Te sugiero contactar al canal de soporte oficial para que puedan explicarte un poco mas sobre los escenarios posibles y el flujo de pagos. https://www.mercadopago.com.ar/developers/es/support/
