### ISSUE TITLE
Error on cancel payment

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#157]
**Describe the bug**
mercadopago/dx-php,  version 1.2.6

**To Reproduce**
```php
$payment = Payment::find_by_id($id);
$payment->status = 'cancelled';
$payment->update();
```
Error "Undefined index: barcode"

**Expected behavior**
Payment cancelled + no error.

**Comment by phgoncalves** [comment]
@nitescent 
Corregimos el problema en la version 1.4.0 del SDK
