### ISSUE TITLE
Enviar parametros adicionales en web tokenize checkout

### ISSUE THREAD

**Issue by idan89** [mercadopago/dx-php#160]
Hola!
No encontre ninguna información en la documentación para poder enviar parametros adicionales al momento de procesar el pago transparente.
Incluí el siguiente código para cargar el checkout:
```
<form action="/procesar-pago" method="POST">
  <script
    src="https://www.mercadopago.com.ar/integrations/v1/web-tokenize-checkout.js"
    data-public-key="TEST-xxxxxxxx"
    data-transaction-amount="100.00">
  </script>
</form>
``` 

Hay alguna forma de enviar algún parámetro extra al enviar el request a **/procesar-pago**? Me interesa enviar información de la dirección al momento de realizar el pago pero no encontre una forma de lograr esto.
Gracias.

**Comment by joelibaceta** [comment]
@idan89 Este canal esta destinado únicamente para la discusion sobre el sdk que aloja este repositorio, bugs, features o ideas del mismo.

Para soporte tecnico general debes dirigirte al canal de soporte oficial: https://mercadopago.com.ar/developers/es/support/
