### ISSUE TITLE
Cómo utilizar el SDK sin Composer?

### ISSUE THREAD

**Issue by Scorpiatus** [mercadopago/dx-php#161]
Hola, necesito utilizar la nueva versión del SDK pero sin utilizar Composer, ya que mi código se distribuye en varios usuarios y no todos tienen la posibilidad de instalarlo?

Intenté hacerlo manualmente, pero siempre faltan clases o salta algún problema.
Gracias de antemano por cualquier ayuda! :P

**Comment by joelibaceta** [comment]
Hola, @Scorpiatus este SDK está diseñado para ser usado con composer y evitar la fragmentación, facilitando que pueda ser fácilmente actualizado a nuevas versiones las cuales son actualizadas frecuentemente.

Si es estrictamente necesario hacerlo manualmente y entiendes las consecuencias de tener un sdk “congelado” en tu proyecto que no reciba actualizaciones nuevas, podrías usar composer de forma local y subir el contenido generado en la carpeta vendor a tu servidor.

**Comment by Scorpiatus** [comment]
Muchas gracias @joelibaceta Funcionó perfecto.

**Comment by alesim0** [comment]
Hola @Scorpiatus te quiero consultar, como hiciste para poder integrar la SDK de MercadoPago, ya que yo estoy intentandolo hacer y no he podido. Cuando ingreso estas líneas de integración me arroja el error Undefined type:

`MercadoPago\SDK::setAccessToken('PROD_ACCESS_TOKEN');`

Me las marca como error y no se exactamente como hacer para hacer la integracion, me podrías ayudar? Te agradezco
