### ISSUE TITLE
Suscripciones trabadas en status Authorized

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#162]
Buenos días @joelibaceta 

Hace varios años que creo suscripciones a través de la API MercadoPago.

Desde hace algunos días todas las suscripciones que creo quedan en el status Authorized, el Invoice queda en status pending y no se genera ningún Payment. Mientras tanto yo sigo enviando los productos a mis clientes suscritos. La situación es urgente.

Están teniendo un problema?
O quizás han cambiado algo en la creación de suscripción y tengo que adaptar el código? No encontré nada en la documentación.

Muchas gracias de antemano por tu ayuda.
También abrí un ticket (30524694) en el Soporte técnico de Mercado Pago, pero en años nunca recibí una respuesta de este soporte.

**Comment by fgilio** [comment]
Me sumo a la consulta

**Comment by joelibaceta** [comment]
@nitescent  Reitero que este canal no esta destinado al soporte general sobre los productos, servicios o APIs de MercadoPago sino únicamente la discusión sobre el SDK contenido en este repositorio de código para la discusión sobre bug o features.

El canal oficial de soporte para desarrolladores es: http://mercadopago.com.ar/developers/es/support/
