### ISSUE TITLE
MercadoPago\Payment::search not working properly

### ISSUE THREAD

**Issue by Workito1** [mercadopago/dx-php#166]
Hello, i would like to report a bug or what i seem to be looking as a bug about the search payment feature.

$filters = array(
			"external_reference" => "06052019_25"
		);
		$options = array(
			"limit" => "50",
			"offset" => "0"
		);
		$payment = MercadoPago\Payment::search($filters, $options);
		echo "<pre>";
		print_r($payment);
		echo "</pre>";

**Describe the bug**
The above code would output all my payments starting from the oldest no matter what i set in filters and options.

**Expected behavior**
I expect to receive only the data that corresponds to the filter or nothing

Thanks

**Comment by Gaspertrix** [comment]
Query params are being cleared when execute() method is called, so all filters are lost.

[https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Manager.php#L75](https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Manager.php#L75)

```
    public function execute($entity, $method = 'get', $options = [])
    {
        $this->cleanQueryParams($entity);
        ....
    }
```

**Comment by Workito1** [comment]
Thanks.
Now it works perfectly.

On May 8, 2019 4:59 PM, Adrian Sachi <notifications@github.com> wrote:

Query params are being cleared when execute() method is called, so all filters are lost.

https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Manager.php#L75

    public function execute($entity, $method = 'get', $options = [])
    {
        $this->cleanQueryParams($entity);
        ....
    }

**Comment by fgilio** [comment]
I have this same problem, any news? Is there any partial fix I could apply?

**Comment by Workito1** [comment]
Look at the answer of gaspertrix. That worked for me.

There is a wrong line de in the file manager.php in the function execute. You have to comment the first line, the one that goes this->cleanqueryparams.... That line is clearing the filters, I assume is an error that line. I commented it and works perfectly now.

**Comment by fgilio** [comment]
Thanks @Workito1, I'll try that. But I don't feel comfortable overloading an SDK class in production.
Just saw there's a PR to fix it, hope it gets merged soon. Thanks @gonzalezfj

**Comment by estudioprogramacaocriativa** [comment]
I also got this error when in composer.json was "mercadopago/dx-php": "dev-master". After update it to the latest version "mercadopago/dx-php": "1.2.1", the search worked perfectly. I hope this help.

**Comment by Workito1** [comment]
Thanks for the answer.
I found a line that was clearing the filters inside a class and that was the problem. I think that line is an error.

On May 18, 2019 10:38 PM, Samuel Santos <notifications@github.com> wrote:

I also got this error when in composer.json was "mercadopago/dx-php": "dev-master". After update it to the latest version "mercadopago/dx-php": "1.2.1", the search worked perfectly. I hope this help.

**Comment by leomargrett** [comment]
Hello, is there any news about the fix of this issue?

I also have problems with \ MercadoPago \ Customer :: search (['email' => $ email]);
It is not filtering the results and it is returning different results to same request.

The solution of  @Gaspertrix seems to be working for me, but as @fgilio says, I neither feel comfortable overloading an SDK class in production. 
Thanks

**Comment by fgilio** [comment]
Long story short, we're overloading that class

**Comment by leomargrett** [comment]
Unfortunately we can't do that on production environment. I hope someone merge this fix. 
Thanks @fgilio

**Comment by vousys** [comment]
@joelibaceta , problema similar al de los chicos, pero aun sigue el bug  en la ultima version
No estoy pudiendo obtener el pago asociado a una preferencia ya que pincha:
```
Uncaught Error: Class 'MercadoPago\SearchResultsArray' not found in 
mercadopago/dx-php/src/MercadoPago/Entity.php:160
``` 

Code:
```
// Busco el pago que exista asociado
$filters = array(
      "external_reference" => $preference_info->external_reference
    );
$options = array(
"limit" => "1",
"offset" => "0"
); 
$payment_info = MercadoPago\Payment::search($filters ,$options );
```
Response:

```
Uncaught Error: Class 'MercadoPago\SearchResultsArray' not found in 
mercadopago/dx-php/src/MercadoPago/Entity.php:160

``` 

Solucion
Hacer un
`include_once "vendor/mercadopago/dx-php/src/MercadoPago/Generic/SearchResultsArray.php";`

**Comment by phgoncalves** [comment]
This issue is fixed in the [latest release](https://github.com/mercadopago/dx-php/releases/tag/1.3.1).

**Comment by fgilio** [comment]
Omg

**Comment by felipemarques** [comment]
when i use ::search method after save a payment ... search returns null ... anyone have this issue ?

**Comment by phgoncalves** [comment]
Hi, @felipemarques .
I did some tests and had no problems. Can you share your code and versions of PHP and SDK?
