### ISSUE TITLE
Bug (typo) in src/MercadoPago/SDK.php

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#169]
```php
public static function delete($uri, $options=[])
    {
      if ($token = self::$_config->get('ACCESS_TOKEN')) {
        $uri = $uri . "?access_token=" . $token;
      }
      return self::$_restClient->deleted($uri, $options);
    }
```

It should be delete
The function name is delete not deleted in mercadopago/dx-php/src/MercadoPago/RestClient.php

**Comment by joelibaceta** [comment]
Thanks @nitescent

**Comment by leomargrett** [comment]
Hello, do you know when is going to be merged this fix?
Thanks

**Comment by phgoncalves** [comment]
@nitescent @leomargrett 
The release 1.3.1 implements this correction.
