### ISSUE TITLE
Existe alguna forma de desvincular una CARD de un CUSTOMER?

### ISSUE THREAD

**Issue by psrosen81** [mercadopago/dx-php#170]
Necesito desvincular CARDS de los CUSTOMERS registrados con anterioridad. No estoy encontrando esta posibilidad en el SDK. Encuentro alguna referencia en los samples, pero con código vacío. E inclusive intente eliminar un cliente haciendo un customer->destroy() pero note que el método tiene una sola linea (y comentada).

Sabrían comentar un poco al respecto, para poder determinar si hay alguna posibilidad de realizar esto. En caso de que no, deberemos controlar de alguna otra forma que tarjetas almacenadas deben mostrarse a los clientes.

Aguardo sus comentarios en cuanto puedan.
Muchas gracias.

**Comment by joelibaceta** [comment]
@psrosen81 me parece que los métodos DELETE no están implementados, pero técnicamente esto se traduciría en un http request con el método **DELETE** a `/customers/:customer_id/cards/:card_id`.

**Comment by psrosen81** [comment]
@joelibaceta gracias por la respuesta. Efectivamente, logre hacerlo de la manera que sugerís.

Simplemente me gustaría mencionar que para ello no use el **dx-php**, me resultó mas sencillo usar para esto el **sdk-php** [(https://github.com/mercadolibre/php-sdk).](https://github.com/mercadolibre/php-sdk) 
Lo explico a continuación por si a alguien le resulta útil.

```
require_once "sdk-php-master/lib/mercadopago.php";

// en este caso loguee con el ACCESS_TOKEN y no con CLIENT_ID y CLIENT_SECRET 
// ya que mi ACCESS_TOKEN apunta a Sandbox. 
// Al cambiar a producción hay que usar el ACCESS_TOKEN de producción.
$mp = new MP('ACCESS_TOKEN'); 

$mp->delete('/v1/customers/178024321-0jeaS97oN26K3A/cards/1557358709876');
```
donde **178024321-0jeaS97oN26K3A** es el customer_id y **1557358709876** es el card_id.

Espero que sea de utilidad.
Saludos!

**Comment by phgoncalves** [comment]
@psrosen81 
En la version 1.5.0 disponibilizamos la funcionalidade para que se pueda desvincular los cards de la siguiente manera:

```
$card = new MercadoPago\Card;
$card->customer_id = '432246298-zuojrWljUNINBx';
$card->id = '8753491926';
$card->delete();
```
