### ISSUE TITLE
Problema al Crear Orden en QR con CURL

### ISSUE THREAD

**Issue by gusgeek** [mercadopago/dx-php#171]
Hola gente.

Tengo este Codigo

```
<?php

$data = array(
    'external_reference' => '7183',
    'items' => array(
        'title' => 'Tacos',
        'currency_id' => 'ARS',
        'unit_price' => 16.0,
        'quantity' => 4
      )
);
 
$payload = json_encode($data);
 
// Prepare new cURL resource
$ch = curl_init('https://api.mercadopago.com/mpmobile/instore/qr/264344950/723902?access_token=APP_USR-XXXXXXXXXXXXX-XXXXXXXXXX');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
 
// Set HTTP Header for POST request 
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Content-Length: ' . strlen($payload))
);
 
// Submit the POST request
$result = curl_exec($ch);
 
// Close cURL session handle
curl_close($ch);
print_r($result);
 
?>
```

(Con el token correcto), al darle accion a este codigo me da este error

> {"error":"invalid_preference_body","message":"Invalid preference_body","status":400,"causes":[]}

¿Cual es el Inconveniente?

Gracias!

**Comment by Javiervanni** [comment]
Hola buenos dias. como estas?
yo tengo el mismo problema pudiste solucionarlo?

Muchas gracias.
Saludos

**Comment by gusgeek** [comment]
> Hola buenos dias. como estas?
> yo tengo el mismo problema pudiste solucionarlo?
> 
> Muchas gracias.
> Saludos

Si Te explico.

- Primero creas el negocio en https://www.mercadopago.com.ar/stores/
- Cuando lo tengas creado, fijate que en la url te da el store_id https://www.mercadopago.com.ar/stores/detail?store_id=1010101010
- Copias el store_id

y procesas este PHP

`<?php

$data = array(
    'name' => 'Suarez QR', <---- ACA NOMBRAS LA CAJA, O EL QR PARA QUE LO IDENTIFIQUES CUANDO LO IMPRIMIS
    'fixed_amount' => true,
    'store_id' => '13050011', <----- ACA PONES EL STORE ID
    'external_id' => '72390001' <---- CREATE UN IDENTIFICADOR INTERNO PARA QUE SEPAS QUE ES ESTE EL QR QUE VAS A USAR.
);
 
$payload = json_encode($data);
 
// Prepare new cURL resource
$ch = curl_init('https://api.mercadopago.com/pos?access_token=APP_USR-token-de-mercadopago');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
 
// Set HTTP Header for POST request 
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Content-Length: ' . strlen($payload))
);
 
// Submit the POST request
$result = curl_exec($ch);
 
// Close cURL session handle
curl_close($ch);
print_r($result);

?>`

Cuando te da el print, te brinda un json como este:

> {"id":1522009,"qr":{"image":"https://www.mercadopago.com/instore/merchant/qr/1522009/25cc76456b8a4b4d89f4bd377de50cf5c6e5f3b0cdc241dd972b7cc51fa55925.png","template_document":"https://www.mercadopago.com/instore/merchant/qr/1522009/template_25cc76456b8a4b4d89f4bd377de50cf5c6e5f3b0cdc241dd972b7cc51fa55925.pdf","template_image":"https://www.mercadopago.com/instore/merchant/qr/1522009/template_25cc76456b8a4b4d89f4bd377de50cf5c6e5f3b0cdc241dd972b7cc51fa55925.png"},"status":"active","date_created":"2019-05-15T22:29:37.000-04:00","date_last_updated":"2019-05-15T22:29:37.000-04:00","uuid":"25cc76456b8a4b4d89f4bd377de50cf5c6e5f3b0cdc241dd972b7cc51fa55925","compatible_id":"c62ecb33af814aeece85cfab4d51c1812569bd8339052c6ae03723784a2a8b69d4144c2e6ada10aafe558b2e9cfa3566be2f1656b928baf85d91911d29cbb2dd","user_id":264344950,"name":"Suarez QR","fixed_amount":true,"store_id":"13050011","external_id":"72390001"}

Si lo lees atentamente, te daras cuenta que te dara un QR distinto al que te crea Mercado Pago automaticamente. Incluso te lo brinda en PNG, PDF, el QR solo sin el branding de Mercado, el uuid, si esta activo, el nombre, store id y el external id. Si obtenes esto, mi amigo, estas al 75% del proceso, felicitaciones.

Solo te queda activar el QR con el monto a pagar. ¿Como?, procesando este PHP:

`<?php

$data = array (
  'external_reference' => '123', <--- REFERENCIA INTERNA DE TU SISTEMA
  'notification_url' => 'www.yourserver.com/endpoint', <----- IPN PARA RECIBIR EL EXTERNAL_REFERENCE y Status del pago
  'items' => 
	array (
	    0 => 
	    array (
	      'title' => 'Nota de Venta: '.$nvi, <--- NOMBRE DE LA VENTA QUE APARECE EN MP Y CLIENTE
	      'currency_id' => 'ARS', <--- MONEDA
	      'unit_price' => 16.0, <--- MONTO
	      'quantity' => 4, <---- CANTIDAD
	    ),
	),
);
 
$payload = json_encode($data);
$ch = curl_init('https://api.mercadopago.com/mpmobile/instore/qr/264344950/7239001?access_token=APP_USR-TOKEN-QUETEDA-MERCADOPAGO');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Content-Length: ' . strlen($payload))
);
$result = curl_exec($ch);
curl_close($ch);
?>
`

Observa esta linea:
https://api.mercadopago.com/mpmobile/instore/qr/264000000/7230000?access_token=APP_USR-TOKEN-QUETEDA-MERCADOPAGO
Donde dice "264000000": lo obtenes del APP_USR-151241xxxxx5942-010600-ds9sex9979020aax46s08a-**264000000**
Donde dice "7230000" : lo obtenes del external_id que le indicaste al crear el QR, acordate que en el jSON te dice. 

cuando tengas completado esto, simplemente ejecuta el PHP-CURL y se activara el QR. Cualquier duda, estoy disponible.

**Comment by gusgeek** [comment]
Para el que quiera saber mas los invito a ver mi sdk  https://github.com/gusgeek/SAPIDK-MercadoPago-PHP
