### ISSUE TITLE
Erro ao atualizar customer

### ISSUE THREAD

**Issue by estudioprogramacaocriativa** [mercadopago/dx-php#173]
Erro retornado ao realizar update de um customer 

herehere1
Fatal error: Uncaught Error: Call to a member function toArray() on null in E:\www\agency\app.mercadopago.com.br\vendor\mercadopago\dx-php\src\MercadoPago\Manager.php:205 Stack trace: #0 E:\www\agency\app.mercadopago.com.br\vendor\mercadopago\dx-php\src\MercadoPago\Entity.php(156): MercadoPago\Manager->setEntityDeltaQueryJsonData(Object(MercadoPago\Customer)) #1 E:\www\agency\app.mercadopago.com.br\src\MercadoPago\Customer.php(75): MercadoPago\Entity->update(Array) #2 E:\www\agency\app.mercadopago.com.br\ajax\process_payment.php(10): PC\MercadoPago\Customer->update_(Array) #3 {main} thrown in E:\www\agency\app.mercadopago.com.br\vendor\mercadopago\dx-php\src\MercadoPago\Manager.php on line 205

Para reproduzir o erro:

$this->access_token = config(ACCESS_TOKEN);
$this->mp = SDK::setAccessToken($this->access_token);
$this->mp = new ModelCustomer();
$resource = $this->mp->update([
    'first_name' => 'user_new_name',
    'last_name' => 'user_new_lastname',
]);

O esperado é um objeto com os dados atualizados do customer

![image](https://user-images.githubusercontent.com/6819427/57976656-85ac0800-79bb-11e9-8418-9f83987db112.png)

**Comment by phgoncalves** [comment]
Olá, @estudioprogramacaocriativa 
Para fazer o update de um customer você deve utilizar um trecho de código parecido com este:
`$customer = MercadoPago\Customer::get('179354799-tcXSVxBAc7bGCD');`
`$customer->first_name = "Nome alterado";`
`$customer->update();`
