### ISSUE TITLE
Problema ao buscar pagamento

### ISSUE THREAD

**Issue by lucassmacedo** [mercadopago/dx-php#174]
Olá! Estou com um problema ao tentar conferir um pagamento.
https://api.mercadopago.com/v1/payments/19751066?access_token=APP_USR-783871039440266-052016-54b0cb67cf51859b27b97a0fa259645f-178046087
Fiz um pagamento via SANDBOX e estou executando esta consulta para conferir o STATUS do pagamento. Porem o retorno é sempre o mesmo "Payment not found"

**Comment by joelibaceta** [comment]
Olá, se o token de acesso usado começar com `APP_USR`, você não está usando credenciais de sandbox.

**Comment by phgoncalves** [comment]
@lucassmacedo 
Como o Joel explicou, o access token utilizado na sua chamada é o do ambiente de produção.
Para fazer chamadas em sandbox utilize as credenciais de sandbox que você pode encontrar neste [link](https://www.mercadopago.com/mlb/account/credentials).
