### ISSUE TITLE
Error metodo ->save() en Symofony

### ISSUE THREAD

**Issue by gonzakpo** [mercadopago/dx-php#176]
Al ejecutar $payment->save();

```
Notice: Undefined index: error
in \vendor/mercadopago/dx-php/src/MercadoPago/Entity.php (line 262)
throw new Exception ($response['error'] . " " . $response['message']);

dump:
$response return:
array:2 [▼
  "code" => 500
  "body" => array:4 [▼
    "message" => "internal_error"
    "error" => null
    "status" => 500
    "cause" => []
  ]
]
```

Symfony 4 PHP 7.3

**Comment by joelibaceta** [comment]
Ese es una respuesta de error 500 del lado del servidor (API), te pasa siempre?

**Comment by gonzakpo** [comment]
Asi es porque no encuentra la clave 'error'
Notice: Undefined index: error

**Comment by fgilio** [comment]
Me acabo de topar con dos incidencias en un log y creo que tienen que ver con esto:
```json
  {
    "function": "handleError",
    "args": [
      8,
      "Undefined index: error",
      "/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php",
      262,
      {
        "options": [],
        "response": {
          "body": {
            "status": 502,
            "message": "Bad Gateway"
          },
          "code": 502
        }
      }
    ],
    "file": "/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php",
    "line": 262,
    "type": "->",
    "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions"
  },
```

**Comment by leomargrett** [comment]
Tengo el mismo problema que reportó @gonzakpo. (Undefined index: error)

Cuando el método $payment->save(); retorna error se intenta lanzar la siguiente excepción: 
throw new Exception ($response['error'] . " " . $response['message']); 

Pero los campos 'error' y 'message' se encuentran dentro de 'body', la excepción debería verse similar a: 
throw new Exception ($response['body']['error'] . " " . $response['body']['message']);

**Comment by phgoncalves** [comment]
@gonzakpo 
El problema se solucionó en las nuevas versiones del SDK.
