### ISSUE TITLE
Es necesario incorporar MercadoPago\SDK::refreshToken($access_token) 

### ISSUE THREAD

**Issue by srok** [mercadopago/dx-php#179]
Hay un problema al crear un pago utilizando la integración con **marketplace**:
si en el mismo flujo queremos guardar las tarjetas del customer (en caso de pago exitoso) no podemos utilizar el **access token de la tienda** ya que está seteado el **access token del vendedor**

Una posible solución es implementar el método **MercadoPago\SDK::refreshToken($access_token) **

`public static function refreshToken($access_token){
      self::setAccessToken($access_token);
      self::$_config->refreshToken();
    }`
 
Esto evita la opción más directa que sería refrescar el token por cada llamada de setAccessToken pero lo habilita para casos especiales.

**Comment by joelibaceta** [comment]
@srok  Quizás esto podría servirte https://github.com/mercadopago/dx-php/wiki/Using-custom-credentials 

RefreshToken en realidad esta destinado para obtener un nuevo token cuando el token actual este vencido.

**Comment by srok** [comment]
Me parece una alternativa mucho mejor a la que propuse. Cierro el issue
