### ISSUE TITLE
Los métodos get de la clase SDK no tienen return 

### ISSUE THREAD

**Issue by srok** [mercadopago/dx-php#180]
Los métodos get de la clase SDK : 

- getAccessToken
- getClientId
- getClientSecret
- getPublicKey

Todos llaman a `self::$_config->get( ` pero sin sentencia **return** 

Deberían devolver el valor del método que están invocando.

**Comment by joelibaceta** [comment]
Tienes razón, tratare de enviar un PR para eso.

**Comment by joelibaceta** [comment]
@srok yo veo un return en **SDK.php** https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/SDK.php#L50

```
public static function getAccessToken(){
      return self::$_config->get('ACCESS_TOKEN');
}
```

**Comment by srok** [comment]
Está agregado en el comit #114  pero no es la versión que bajó composer cuando lo instalé hace menos de un mes. ¿está actualizado en el repositorio de composer?

**Comment by joelibaceta** [comment]
Entiendo, asumo que debería estar incluido en el siguiente release, creo que estaban revisando un PR pendientes sobre el search antes de de desplegar la nueva versión.
