### ISSUE TITLE
Customer::search devuelve el resultado de la request anterior

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#183]
composer.json `"mercadopago/dx-php": "^1.2"`
composer.lock `"name": "mercadopago/dx-php",
"version": "1.2.7"`

\MercadoPago\Customer::search(['email' => $email]);

El search devuelve el resultado de la request anterior.

**Comment by joelibaceta** [comment]
@Juanii95 me parece que este puede ser un bug que este PR debería resolverlo https://github.com/mercadopago/dx-php/pull/172

**Comment by nitescent** [comment]
@joelibaceta no entendí. Esta solucionado?

**Comment by nitescent** [comment]
@joelibaceta cómo estás? Sigo teniendo el problema

**Comment by joelibaceta** [comment]
@nitescent como comente en otro issue, personalmente ya no estoy manteniendo este repo de forma activa, por ello solicite que puedan revisarlo desde MercadoPago, si esto no pasa en un tiempo hace el merge en mi Fork personal.

**Comment by nitescent** [comment]
@joelibaceta la solución es comentar `$this->cleanQueryParams($entity);` en el método execute de src/MercadoPago/Manager.php ?

**Comment by leomargrett** [comment]
Hay alguna novedad respecto de este hilo? 

Yo también estoy teniendo problemas con el \MercadoPago\Customer::search(['email' => $email]);
No me está filtrando los resultados, e incluso arroja distintos resultados para idénticas consultas.

Estuve probando la solución que propuso @nitescent y pareciera funcionar bien. Alguién pudo revisar este problema?

**Comment by phgoncalves** [comment]
@nitescent 
El problema está resuelto en la version [1.3.1](https://github.com/mercadopago/dx-php/releases/tag/1.3.1).
