### ISSUE TITLE
PHP Notice "Undefined index: barcode" en Payment update() para cancelar pago ticket.

### ISSUE THREAD

**Issue by Agusfn** [mercadopago/dx-php#195]
Hice la prueba con varios pagos de pago facil pendientes y tira ese aviso. Se cancela correctamente igual.

![imagen](https://user-images.githubusercontent.com/4635809/59970302-ed182300-9538-11e9-8a10-a9886b333135.png)

**Comment by CanuMarcel** [comment]
Me paso lo mismo!! 
Al parecer esperan como status 'canceled' no 'cancelled'
Probe con eso y funcionó.
