### ISSUE TITLE
Atributos gets da Classe SDK retornam null

### ISSUE THREAD

**Issue by wesleydeveloper** [mercadopago/dx-php#196]
Olá, Sou Wesley Silva, desenvolvedor web.
Estou Integrando esse sdk num sistema estruturado de um cliente e observei que a vários bugs.

1º - Na classe Payer não existe os atributos first_name e last_name, o que tem lá é name e surname.

2º - Depois de varias tentativas de comunicação com a api sem sucesso no sandbox. Fui tentar criar uma função para verificar se estava usando access token ou client id e descobri que os atributos gets da classe sdk não retornam valor algum. O certo seria retornar a string que foi configurada anteriormente em setAccessToken ou um simples booleano. Parâmetros testados: getAccessToken, getClientId, getClientSecret.

3º - Se setar um pagamento com vários atributos de um usuário, simplesmente não funciona.

4º - Se setar um pagamento somente com o email do usuario, a aprovação demora uma eternidade.

Gostaria de soluções para isso.

**Comment by phgoncalves** [comment]
Olá, @wesleydeveloper .
1º - Na classe payer existem os atributos first_name e last_name. [Link](https://github.com/mercadopago/dx-php/blob/2f701a07d785a3adecbdc14d27ffa4c36b96532f/src/MercadoPago/Entities/Shared/Payer.php#L34-L40)

2º e 3º - Pode compartilhar o trecho de código e a reposta do SDK para analisarmos?

4º - Pode detalhar um pouco melhor o problema? A resposta da API demora ou o pagamento é criado e fica pendente de aprovação. Compartilhe também o código e a resposta.
