### ISSUE TITLE
Error en el metódo setEntityUrl de la clase Manager.php cuando se utiliza SDK::setPublicKey con save entity

### ISSUE THREAD

**Issue by matias-wobiz** [mercadopago/dx-php#198]
> For support request no related with bugs or feature requests for this SDK, please use the official developers support channel https://mercadopago.com.ar/developers/es/support/

**Describe the bug**
Error en el método setEntityUrl de la clase Manager.php linea 159 "str_replace() expects at least 3 parameters, 2 given" 

**To Reproduce**
1. Setear el SDK::setPublicKey("publickey")
2. $cardToken = new \MercadoPago\CardToken();
    $cardToken->card_id = $card->gateway_card_id;
    $cardToken->save();
3. Ver el error "str_replace() expects at least 3 parameters, 2 given" 

**Expected behavior**
Se espera que devuelva el token

**Additional context**
Ya se ha realizado un primer pago con la tarjeta y se necesita regenerar el token para realizar los pagos siguientes. Si se pasa el tercer parámetro de url en str_replace el comportamiento es el esperado. https://github.com/mercadopago/dx-php/blob/615f97f577adc404e84126e121af6820e8250d38/src/MercadoPago/Manager.php#L159

**Comment by pablorsk** [comment]
Tengo el mismo problema ojalá fusionen pronto el fix propuesto: #202

**Comment by phgoncalves** [comment]
@matias-wobiz @pablorsk 
Gracias por reportar el problema.
El fix está disponible en el release [1.3.1](https://github.com/mercadopago/dx-php/releases/tag/1.3.1)

**Comment by diego-sorribas** [comment]
Buenas, En el $_manager tengo seteado el Access Token pero aún así me pide el public_key está bien eso?

Porque me tirá: Invalid access parameters. Should specify a public_key or an access_token to POST a CardToken
