### ISSUE TITLE
La version del SDK no se actualiza en cada release

### ISSUE THREAD

**Issue by nicoandrade** [mercadopago/dx-php#199]
Si no me equivoco, la versión del SDK se debería actualizar en cada release, en esta linea:
https://github.com/mercadopago/dx-php/blob/615f97f577adc404e84126e121af6820e8250d38/src/MercadoPago/Version.php#L6

Sino no veo de que forma se puede saber que versión del SDK se está usando.

Gracias.

**Comment by joelibaceta** [comment]
Ahi propuse el cambio https://github.com/mercadopago/dx-php/pull/200 en un PR

**Comment by phgoncalves** [comment]
@nicoandrade 
Pasamos a actualizar la version en todos los releases.
Gracias por el reporte!
