### ISSUE TITLE
Cual es el Objetivo de payment_methods

### ISSUE THREAD

**Issue by ultramix** [mercadopago/dx-php#209]
Buenos días y disculpas por adelantado si la pregunta suena muy tonta, pero en si cual es el funcionamiento de la opción payment_methods de preference, pues no importa que métodos o tipos de pagos excluya siempre aparecen todos disponibles al momento de realizar el pago.

**Comment by gusgeek** [comment]
Podes habilitar ciertos modos de pago, como solo visa o no aceptar rapipago

**Comment by phgoncalves** [comment]
Hola, @ultramix 
Hice pruebas y el comportamiento fue el esperado. Por ejemplo, agregando el código abajo no se permite pagos con tarjetas master.
`$preference->payment_methods = array(
    "excluded_payment_methods" => array(
        array("id" => "master")
    )
);`

Cuál és la version de SDK que estás utilizando?
Puedes compartir su código aqui?

**Comment by ultramix** [comment]
Hola y perdón por la respuesta tardía,, vi que mi error era el que no había comprendido bien el como usarlo pero al checar nuevamente lo pude hacer sin más problemas, aun así muchas gracias por su ayuda.
