### ISSUE TITLE
Las notificaciones no llegan

### ISSUE THREAD

**Issue by grandemestre** [mercadopago/dx-php#223]
Vendo por enlace de pago y me gustaría usar notificaciones para hacer envíos automáticos.

Fui a:
https://www.mercadopago.com/mlb/account/webhooks

Configuro la URL

![mperro2](https://user-images.githubusercontent.com/18264177/65574770-acb7af00-df44-11e9-8488-22e8ec7986af.jpg)

La página tiene este código solo para pruebas:
```
$data = file_get_contents('php://input');
$data2 = $_POST;
$value = $_REQUEST;
if($data || $data2){

    $fp = fopen('file.txt', 'a+');
    fwrite($fp, $data);
    fwrite($fp, '2'+json_encode($data2));
    fclose($fp);
}elseif($value){

$fp = fopen('file2.txt', 'a+');
    fwrite($fp, json_encode($value));
    fclose($fp);
}
```
Si hago clic en "Testar", recibo la notificación correctamente, pero cuando se producen ventas reales, las notificaciones no llegan

**Comment by gusgeek** [comment]
Proba con mi SDK de MP https://github.com/gusgeek/SAPIDK-MercadoPago-PHP

**Comment by phgoncalves** [comment]
@grandemestre 
Como no se trata de um problema con el SDK és necesario que reporte el problema por este canal:
https://www.mercadopago.com.br/developers/pt/support/
