### ISSUE TITLE
Smart Checkout: Boton Volver al Sitio no funciona

### ISSUE THREAD

**Issue by andreszs** [mercadopago/dx-php#227]
En **Smart Checkout** al finalizar un pago (ya sea con efectivo o tarjeta) el boton para _**Volver al Sitio**_ no hace nada. Esto es, cuando por usar un dispositivo movil el SDK redirige a www.mercadopago.com en vez de usar el form modal, nunca se puede volver al sitio de origen.

Estoy seteando los `back_urls` asi:
```
    // Crear URLs de retorno para el proceso finalizado
    $preference->back_urls = array(
        "success" => 'https://'.$_SERVER['SERVER_NAME'].'/test_mp/?success',
        "failure" => 'https://'.$_SERVER['SERVER_NAME'].'/test_mp/?failure',
        "pending" => 'https://'.$_SERVER['SERVER_NAME'].'/test_mp/?pending',
   );
```

Setear `$preference->auto_return` tampoco hace ninguna diferencia, no hay ninguna auto-redirección al sitio de origen al terminar un pago como señala la [documentación](https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/advanced-integration/#bookmark_url_de_retorno).

### Screenshots ###
Ninguno de estos botones que deberian volver al site hace nada, como hago para corregir esto y volver al sitio indicado por los back_urls? Gracias desde ya

![image](https://user-images.githubusercontent.com/10298071/66753209-ae043980-ee69-11e9-8836-791811af3948.png)

### Additional context ###
Modo SANDBOX, cuando el SDK redirige a mercadopago.com en vez de usar formulario MODAL.

**Comment by gusgeek** [comment]
En modo dev nunca anda, proba con cuentas de verdad.. proba con mi SDK https://github.com/gusgeek/SAPIDK-MercadoPago-PHP

**Comment by andreszs** [comment]
@gusgeek Gracias, revise el README pero no me queda claro que hace tu SDK, no hay ejemplos, referencia de uso, screenshots ni demo URL. Otra cosa, el source code tiene demasiado whitespace y la falta de formato e indentacion pareja hace imposible tratar de leerlo. Fuera de eso, es cierto que el modo sandbox tiene varias cosas raras, por ejemplo no llegan reportes IPN para actualizar las ordenes, solo parece llegar el primer IPN de orden generada.

**Comment by userpanky** [comment]
Que raro... Pues si leíste el README deberías haber visto de que todo esta en la Wiki. Bueno. Suerte entonces!!!

**Comment by gusgeek** [comment]
@andreszs, gracias por tu crítica. Lo tendré en cuenta. Bien dice el colega, en la Wiki tenés la información de cómo funciona. Y la función es mucho más clara que el propio SDK de No, es cuestión de leerlo, se entiende. Después de todo fue un aporte, suerte con tu desarrollo. Seguro te irá bien.

**Comment by andreszs** [comment]
Cierro el tema porque implementé el modo REDIRECT para los usuarios moviles, y al hacer esto el boton Volver al Sitio funciona correctamente. Solo falla en modo sandbox, si no se especifica el modo redirect.

**Comment by gusgeek** [comment]
> Cierro el tema porque implementé el modo REDIRECT para los usuarios moviles, y al hacer esto el boton Volver al Sitio funciona correctamente. Solo falla en modo sandbox, si no se especifica el modo redirect.

Fue un gusto colaborarte. Saludos.

**Comment by feliarana** [comment]
Buenas. A mi no me esta funcionando tengo exactamente el mismo problema. Desde el mobile redirige al sitio de mercado pago y no me fuinciona le boton al querer volver al sitio.

**Comment by federicoprimomo** [comment]
tengo el mismo problema @feliarana  @andreszs tanto en modo sandbox como produccion, pero solo en usuarios mobile, incluso en modo mobile del depurador del chrome desde la pc.
ayuda!
