### ISSUE TITLE
Pagamentos recusados

### ISSUE THREAD

**Issue by lucaspaulino** [mercadopago/dx-php#229]
Boa noite,
Tenho várias reclamações de meus clientes, informando que o pagamento utilizando mercado pago foi recusado. 
São vários pagamentos seguidos.

Existe alguma forma de corrigir isto? É o código?

Pois quando eles criam o link diretamente no painel, os pagamentos são efetuados normalmente.

**Comment by phgoncalves** [comment]
Olá, @lucaspaulino 
A nível de código você precisa se certificar que o frontend foi implementado seguindo os padrões expostos [nessa documentação](https://www.mercadopago.com.br/developers/pt/guides/payments/api/introduction/).
Além disso é necessário enviar o maior número de informações possíveis sobre a venda e o comprador. Essas informações são enviadas no campos additional_info no momento da criação do pagamento. Você pode conferir todos os campos suportados [aqui](https://www.mercadopago.com.br/developers/pt/reference/payments/_payments/post/).

Caso os pontos acima estejam ok o ideal é que você entre em contato com a [central de ajuda](https://www.mercadopago.com.br/ajuda). Pois assim será possível analisar os casos de forma mais profunda.
