### ISSUE TITLE
Wrong type NULL. It should be integer for property sponsor_id

### ISSUE THREAD

**Issue by ecolasurdo** [mercadopago/dx-php#251]
De un día para el otro me empezó a pedir sponsor_id al crear una **preferencia**.

El error es: 
Wrong type NULL. It should be integer for property sponsor_id

El problema es que si cambio el Client ID y Client Secret por otro de un usuario normal, me permite generar la preferencia. Estuve viendo y la cuenta no tuvo cambios y en la documentación no indica nada sobre el sponsor_id.

SDK v1.8.0.

**Comment by fgilio** [comment]
Estoy con exactamente el mismo error, por ahora me pasa con una sola cuenta de entre varias.
Vi que al crear la preferencia con el cliente que falla la respuesta de la API [incluye el sponsor_id](https://user-images.githubusercontent.com/6857732/77314994-8309f580-6ce5-11ea-8f46-2699a6571581.png), pero en las respuestas de los clientes que no fallan no [está el sponsor_id.](https://user-images.githubusercontent.com/6857732/77314988-80a79b80-6ce5-11ea-85a6-b03782101a07.png)

**Comment by ecolasurdo** [comment]
@fgilio No se si te pasa o no lo siguiente:
1. Establezco mi USER ID en el sponsor_id
2. Me permite generar la **preferencia**.
3. Hago el pago y me aparece un error en MercadoPago que dice: 
_Oh, no, algo anduvo mal._

**Comment by fgilio** [comment]
No probé haciendo eso, encontraste documentación de qué es el sponsor id?

**Comment by ecolasurdo** [comment]
Si. Rarísimo, está en la documentación para el pago con QR:
https://www.mercadopago.com.ar/developers/es/guides/qr-code/general-considerations/pre-requisites/
_Es el collector_ID del usuario proveedor del sistema integrado con Mercado Pago. El sponsor_ID no puede ser igual al collector_id_
Pero en nuestro caso no lo tenemos implementado.

**Comment by fgilio** [comment]
Interesante, es la primera vez que veo ese parámetro. Me hace pensar que están implementando estos cambios en la API, pero no veo nada en el changelog: https://www.mercadopago.com.ar/developers/es/guides/changelog/current-year/

Espero que la gente de MP nos pueda responder pronto.

**Comment by ecolasurdo** [comment]
Si. Lo mismo hice, fijarme en el changelog. Esperemos que respondan pronto. 
Si me contestan por alguno de los medios donde hice el reclamo aviso aca también.
Gracias @fgilio

**Comment by gutitrombotto** [comment]
Yo tuve exactamente el mismo error.

La prueba que realicé es hacer exactamente la misma request que hago a través de la sdk de php con un cliente (Postman).
En esa prueba, la preferencia se crea perfectamente.
Conclusión, el problema está en la sdk de mercado pago.

Por lo tanto, fui a la librería dx-php, en la clase Preference, está puesto que el tipo de dato del sponsor_id es integer.
Entonces, cuando se realiza la comprobación del tipo en la clase Entity (función tryFormat), se valida que el formato 'null' devuelto por la api es incorrecto y salta el error.
Si no me equivoco, el sponsor_id hace referencia a si usamos una plataforma de pagos como 'Prestashop'. Yo tengo implementado un Marketplace, no tengo por que tener asignado un sponsor_id.

Finalmente, para 'resolver el error' (y lo pongo entre comillas por que no se debe hacer esto, simplemente hice la prueba para chequear que realmente funcionara) cambíe la siguiente linea:
    /**
     * @Attribute(type = "integer")
     */
    protected $sponsor_id;

Por:
    /**
     * @Attribute()
     */
    protected $sponsor_id;

Y comenzó a funcionar. Basicamente, el motivo por el que funciona parecería ser que es por no hacer el chequeo del tipo.

Supongo que en pull request #253 se arregla este problema. 
Dejo este comentario para saber por que sucede.

Espero que les sirva!

**Comment by ecolasurdo** [comment]
Actualicé el SDK y efectivamente está funcionando bien.

**Comment by phgoncalves** [comment]
La version [1.8.1](https://github.com/mercadopago/dx-php/releases/tag/1.8.1) resuelve este problema.
