### ISSUE TITLE
Problem with autoload

### ISSUE THREAD

**Issue by diego-sorribas** [mercadopago/dx-php#37]
Hi, I have issues with the autoload when I want to use the SDK class, I think is because when composer try to load the class it has diferente name betweeen the file and the class name, I think it must be class Sdk

**Comment by joelibaceta** [comment]
Which version are you using?

**Comment by diego-sorribas** [comment]
dev-master

**Comment by joelibaceta** [comment]
SDK class exists into MercadoPago namespace (https://github.com/mercadopago/dx-php/blob/master/src/MercadoPago/Sdk.php).

**Comment by imasson** [comment]
Joel, file name MUST match class name for autoload to find it. Case sensitive.
I had to make a fork and fix that in order to use the sdk.

**Comment by joelibaceta** [comment]
@imasson  thanks, PRs are welcome :D 👍

**Comment by imasson** [comment]
Hey, i already sent a pr with this a time ago.

![screenshot from 2018-03-19 10-56-52](https://user-images.githubusercontent.com/8289723/37599798-56acfa74-2b64-11e8-8eca-2e30e84ec6ef.png)

**Comment by joelibaceta** [comment]
Done, Merged 👍
