### ISSUE TITLE
Class exists is not autoloading the class.

### ISSUE THREAD

**Issue by extqy** [mercadopago/dx-php#41]
I think this is a problem, because I had to change to "true", and so it worked:
https://github.com/mercadopago/dx-php/blob/470a7ecd5a84c83894b015fb2455be24df31e023/src/MercadoPago/Entity.php#L349-L353

**Comment by joelibaceta** [comment]
Thanks for report, we made the changes requested in https://github.com/mercadopago/dx-php/pull/48  , we invite you to make a pull request for the next time 👍
