### ISSUE TITLE
Problema con la integracion

### ISSUE THREAD

**Issue by erusconi** [mercadopago/dx-php#42]
Hola tengo problemas con la integracion. Instale el composer realice todo lo referido a los tutoriales de MP, pero me tira este error: 

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /Applications/XAMPP/xamppfiles/htdocs/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50

Espero respuesta

**Comment by diego-sorribas** [comment]
Es un problema con la versión de PHP, fijate que versión tenes instalado en el xampp.
