### ISSUE TITLE
$payment->save(); doesn't respond

### ISSUE THREAD

**Issue by doulos77** [mercadopago/dx-php#44]
Estaba haciendo pruebas satisfactorias en modo SandBox pero al tratar de hacer una prueba en modo de producción dejó de enviar la respuesta el $payment->save() con lo que no puedo ver el $payment->status aunque sigo intentando con el modo SandBox.

**Comment by diego-sorribas** [comment]
No te da ningún error?

**Comment by doulos77** [comment]
@diego-sorribas 
Hola, no. Y sí está generando correctamente el token del pago.

**Comment by diego-sorribas** [comment]
Una pregunta si vas a buscar el pago con el ID de payment que devuelve podes ver el status? SIno me equivoco seria algo asi:

`$payment = Payment::find_by_id($paymentId);`

**Comment by doulos77** [comment]
No, tampoco.

**Comment by diego-sorribas** [comment]
Y si le pegas derecho al endpoint:
`https://api.mercadopago.com/v1/payments/[PAYMENT_ID]?access_token=[TOKEN]`

Te lo devuelve?

**Comment by doulos77** [comment]
Si lo hago directo me da:
"message": "Malformed access_token:
Aunque el access token es el correcto.

**Comment by doulos77** [comment]
Si lo intento así:
`https://api.mercadopago.com/v1/payments/[PAYMENT_ID]`
Me marca:
`"error": "not_found",  "status": 404,`
Lo que parece indicar que `$payment->save();` no está procesando el pago.

**Comment by diego-sorribas** [comment]
Tiene que ir con el AT, probaste con el de pruebas y el de producción?

**Comment by doulos77** [comment]
Sí, ya lo intenté con ambos.

**Comment by doulos77** [comment]
El problema era que estaba tratando de hacer una prueba de pago con $1.00 peso siendo que la mayoría de los métodos de pago disponibles deben ser desde $5.00 pesos. Esta era la razón de que el pago no se procesara, sin embaro, no me fue fácil encontrar dicha información.
De cualquier forma gracias @diego-sorribas por la atención.

**Comment by diego-sorribas** [comment]
@doulos77 Me alegro que le encontraste la vuelta, en este link esta la info de los mínimos:

https://api.mercadolibre.com/sites/MLU/payment_methods/visa?marketplace=NONE

Cambiale el MLU por el país que necesites y el método de pago.

**Comment by joelibaceta** [comment]
Gracias @diego-sorribas @doulos77 vamos a tratar de mejorar la visibilidad de estos errores de frontera en las integraciones. issue https://github.com/mercadopago/dx-php/issues/47

**Comment by macabrera** [comment]
Hola gente, tengo una consulta relacionada con esto. Estoy haciendo la prueba del sdk normal como en el tutorial, sin nada agregado, y cuando llamo a save de payment no hace nada, o sea me devuelve un objeto con todo nulo, sin status sin nada parecido, ¿que podra ser? Gracias.

Este es mi codigo: https://www.mercadopago.com.ar/developers/es/guides/payments/api/receiving-payment-by-card

<?php  
    // SDK de Mercado Pago
    require __DIR__ .  '/vendor/autoload.php';
    MercadoPago\SDK::setAccessToken("TEST-4889631565706028-090713-6ddb3ce82c16c1ae3f7f6aa2e113b3fb__LD_LC__-75481956");

    $payment = new MercadoPago\Payment();
    $payment->transaction_amount = 123;
    $payment->token = $_POST["token"]; //Este viene del formulario de la pagina anterior correctamente
    $payment->description = "Rustic Linen Computer";
    $payment->installments = 1;
    $payment->payment_method_id = "master";
    $payment->payer = array("email" => "example@example.com");

    // Save and posting the payment
    $response = $payment->save();
    // Print the payment status
    var_dump($response);
    var_dump($payment);
?>

Gracias. Saludos.

**Comment by joelibaceta** [comment]
Revisaste esto ? https://github.com/mercadopago/dx-php/wiki/Error-Handling
