### ISSUE TITLE
IPN en dx SDK?

### ISSUE THREAD

**Issue by ezetojo** [mercadopago/dx-php#50]
Estoy implementando el nuevo SDK, lo que me encuentro, incluso en la nueva documentación es que para utilizar las notificaciones (IPN) debo usar el SDK anterior. En qué tiempo calculan se implementará para no tener que estar usando ambos?

**Comment by joelibaceta** [comment]
@ezetojo  me parece que es un error de documentación, gracias por la observación.

**Comment by vousys** [comment]
@joelibaceta sabes que recien estoy integrando ésta nueva version en el IPN y no puedo recuperar los preferencias, buscandolas por el id:
```

$preference         = new MercadoPago\Preference();
$preference_info = $preference->find_by_id($preference_id);

```
Me devuelve el siguiente error, pruebe con el ID que pruebe

Fatal error: Uncaught exception 'Exception' with message 'Error required in attribute items' in /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php:99 Stack trace: #0 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(82): MercadoPago\Manager->validateAttribute(Object(MercadoPago\Preference), 'items', Array) #1 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(90): MercadoPago\Manager->execute(Object(MercadoPago\Preference), 'get') #2 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(57): MercadoPago\Entity::read(Array) #3 /var/www/crons/mercadopago-ipn.php(79): MercadoPago\Entity::find_by_id('272247088-d156f...') #4 {main} thrown in /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php on line 99

**Comment by joelibaceta** [comment]
@vousys me parece que ese podría ser un issue distinto al que comenta @ezetojo :)

**Comment by joelibaceta** [comment]
@ezetojo Solved in https://github.com/mercadopago/devsite-docs/issues/171
