### ISSUE TITLE
Call to undefined method MercadoPago\Preapproval::load()

### ISSUE THREAD

**Issue by doulos77** [mercadopago/dx-php#51]
Hola, estoy tratando de cancelar un pago siguiendo el ejemplo que aparece en la guía de integración: (https://www.mercadopago.com.mx/developers/en/guides/manage-account/cancellations-and-refunds).
Sin embargo, al tratar de cargar el pago con el método: `MercadoPago\Preapproval::load($payment_id);` para poder cambiar su status. PHP me arroja el siguiente error: Fatal error: Uncaught Error: Call to undefined method MercadoPago\Preapproval::load() por lo que no puedo cancelar el pago.

**To Reproduce**
1. Intentar cargar un pago con el método: `MercadoPago\Preapproval::load($payment_id);`
2. PHP arroja el error: Fatal error: Uncaught Error: Call to undefined method MercadoPago\Preapproval::load()

**Expected behavior**
Cargar el pago para poder cambiar su estatus a cancelled y hacer update.

**SDK:**
 - dx-php (Composer)

**Comment by doulos77** [comment]
Hola.
Al final tuve que usar el SDK anterior para poder cancelar el pago:
https://www.mercadopago.com.mx/developers/es/tools/sdk/server/php/

**Comment by joelibaceta** [comment]
Hola @doulos77 disculpa la falta de actualización del snippet, estamos trabajando en eso, como indicamos en el readme de este repositorio y con un objetivo de estandarización, unificamos el naming de los metodos y `load($id)` ahora es `find_by_id($id)`;

**Comment by lsfiege** [comment]
deberian actualizar la documentación, me comí el mismo error y terminé buscando acá para ver que pasó

**Comment by fgilio** [comment]
Cómo comentaba en https://github.com/mercadopago/dx-php/issues/62, al igual que @doulos77 terminé usando el SDK viejo para cancelar suscripciones.
Entiendo que están planeando una solución superadora para el manejo de suscripciones, pero estaría bueno que en el mientras tanto nos den algo que funcione. Guste o no, hay mucho legacy que funciona con los pre approval.

**Comment by joelibaceta** [comment]
@lsfiege en la documentación fueron retiradas las secciones sobre suscripciones.
