### ISSUE TITLE
getAllPaymentMethods - Obtener la imagen de la tarjeta + Promociones bancarias

### ISSUE THREAD

**Issue by vousys** [mercadopago/dx-php#52]
Hola!

Estaria buenisimo si en el SDK de Javascript, en el metodo:  Mercadopago.getAllPaymentMethods(onsuccess)
Ademas de los thumb del logo de la tarjeta que envian, podrian enviar tambien la imagen de la tarjeta como se ven en el workflow de la app movil de uds. (adjunto captura de refe)

![image](https://user-images.githubusercontent.com/12813221/41927676-3ff1f6b2-7949-11e8-985d-f60a4102e2bc.png)

Y si no es demasiado pedir, seria un golazo que el JSON nos devuelva, por cada uno de los metodos, las promociones que tiene vigentes, para evitar N request.

**Comment by joelibaceta** [comment]
Estamos trabajando en poder liberar y abrir a la comunidad el SDK de JS, con el fin de poder apoyarnos en la comunidad de sugerencias e ideas.
