### ISSUE TITLE
No hay forma de eliminar una card de un customer?

### ISSUE THREAD

**Issue by nicoandrade** [mercadopago/dx-php#53]
No veo forma alguna de eliminar una card de un customer.
En la documentación no hay nada y acá en los ejemplos, están los archivos pero están vacíos:
https://github.com/mercadopago/dx-php/blob/master/samples/customer-and-cards/customer/cards/remove.php

**Comment by joelibaceta** [comment]
@nicoandrade podes hacer un request HTTP con el metodo **DELETE** hacia el endpoint `/customers/:customer_id/cards/:id` para eliminar una tarjeta, estamos trabajando en incluir los metodos delete en el SDK.
