### ISSUE TITLE
Error al buscar preferencias por el ID

### ISSUE THREAD

**Issue by vousys** [mercadopago/dx-php#54]
Al intentar recuperar el status de las preferencias, buscandolas por id , de la siguiente manera:

```
$preference         = new MercadoPago\Preference();
$preference_info    = $preference->find_by_id($preference_id);
```
 
Me devuelve el siguiente error, pruebe con el preference ID que pruebe:

Fatal error: Uncaught exception 'Exception' with message 'Error required in attribute items' in /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php:99 Stack trace: #0 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(82): MercadoPago\Manager->validateAttribute(Object(MercadoPago\Preference), 'items', Array) #1 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(90): MercadoPago\Manager->execute(Object(MercadoPago\Preference), 'get') #2 /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(57): MercadoPago\Entity::read(Array) #3 /var/www/crons/mercadopago-ipn.php(79): MercadoPago\Entity::find_by_id('272247088-d156f...') #4 {main} thrown in /var/www/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php on line 99

**Comment by joelibaceta** [comment]
@vousys  no es necesario instancias un objeto `Preference` para llamar a `find_by_id` ya que es una función estática.

La forma correcta es:

`MercadoPago\Preference::find_by_id($preference_id);`

**Comment by vousys** [comment]
Hola Joel, che sabes q lo cambie recien pero me da la misma exeption 'Error required in attribute items'"
Me tengo que actualizar el sdk?

**Comment by joelibaceta** [comment]
@vousys podrías compartirme el id de la preferencia que estas usando, me parece que puede ser un bug al poblar la instancia `preference` a partir de la respuesta del API, al considerar un atributo obligatorio, pero este llega vacío.

**Comment by vousys** [comment]
Muchas gracias por el support ! te paso 2.
Ambas ordenes fueron creadas con el sdk viejo.

272247088-7f825141-224b-408e-a855-02aadafd07a7      19/06/2018 11:42
272247088-8e3f3d07-c591-49c3-8daf-4e155f44c6ed      18/06/2018 12:29

**Comment by vousys** [comment]
Joel, te dejo anotado aca que el search  de las preference, tampoco anda:

```
       $search_filter = array(
                                          "external_reference" => $external_reference
                                        );
     $payment_info = MercadoPago\Preference::search($search_filter);


```
Fatal error: Uncaught exception 'Exception' with message 'ORM method search not available for entity:MercadoPago\Preference' in /home/xxxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php:126 Stack trace: #0 /home/xxxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(108): MercadoPago\Manager->setEntityUrl(Object(MercadoPago\Preference), 'search') #1 /home/xxxx/public_html/xxxx/mercadopago-ipn.php(109): MercadoPago\Entity::search(Array) #2 {main} thrown in /home/xxxxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php on line 1

**Comment by joelibaceta** [comment]
Como indica el error `ORM method search not available for entity:MercadoPago\Preference` el metodo `search` no esta disponible para la entidad `Preference` ya que el API aun no lo soporta.

**Comment by vousys** [comment]
Ok, si entendi el mensaje. Simplemente estaba tratando de probar alguna otra alternativa para recuperar la preferencia y poder volver a tener el IPN andando con el sdk nuevo.  Como la clase pertenece a Entity y no encontre documentacion de todas las funciones q tenia habiitadas cada entidad, me parecio util enviartelo, pero podes sentirte libre de eliminarlo si no corresponde.

**Comment by joelibaceta** [comment]
Gracias por el reporte, en breve me tomo un tiempo de revisar el fix para este issue.

**Comment by vousys** [comment]
Dale, gracias!

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-php/pull/60

**Comment by vousys** [comment]
Hola Joel, perdoname q te moleste nuevamente... sabes q me sigue el problema.
Me actualice el sdk pero me salta lo mismo

trans:272247088-24457e1f-54e7-4b33-9d85-14ee87be73e6 

Creando preferencia
find_by_id: 
Fatal error: Uncaught exception 'Exception' with message 'Error required in attribute items' in /xxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php:99 Stack trace: #0 /xxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(82): MercadoPago\Manager->validateAttribute(Object(MercadoPago\Preference), 'items', Array) #1 /xxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(90): MercadoPago\Manager->execute(Object(MercadoPago\Preference), 'get') #2 /xxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(57): MercadoPago\Entity::read(Array) #3 /xxx/public_html/crons/mercadopago-ipn.php(100): MercadoPago\Entity::find_by_id('272247088-24457...') #4 {main} thrown in /xxx/public_html/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php on line 99

**Comment by joelibaceta** [comment]
@vousys correcto, quedaba pendiente actualizar la versión en Composer, puedes probar ahora, apuntando a dev-master

**Comment by joelibaceta** [comment]
La version 1.1.2 ha sido subida a Composer y la versión en Master resuelve este issue, añadimos un Test para validar este escenario en futuras modificaciones https://github.com/mercadopago/dx-php/blob/master/tests/resources/PreferenceTest.php#L41.

**Comment by vousys** [comment]
Voy a bajarlo todo de vuelta y lo pruebo.
Podra tener que ver con que la preference fue creada con el SDK viejo?

**Comment by joelibaceta** [comment]
No, ya que el API sigue siendo el mismo.
