### ISSUE TITLE
Problema al buscar pago por referencia externa

### ISSUE THREAD

**Issue by emiliodeg** [mercadopago/dx-php#55]
**Describe the bug**
Al buscar un pago por referencia externa genera un error `Undefined offset 0`

**To Reproduce**
```php
$payment = Payment::search(['external_reference' => $codigoDeRastreo]);
```
Error generado en MercadoPago\Entity.php:113

Respuesta del API
```
array(2) {
  ["code"]=&gt;
  int(200)
  ["body"]=&gt;
  array(2) {
    ["paging"]=&gt;
    array(3) {
      ["total"]=&gt;
      int(0)
      ["limit"]=&gt;
      int(30)
      ["offset"]=&gt;
      int(0)
    }
    ["results"]=&gt;
    array(0) {
    }
  }
}
```

**Server (please complete the following information):**
 - OS: Windows y Linux
 - Apache y Nginx
 - PHP 7.2.4

**Comment by joelibaceta** [comment]
Probably solved in https://github.com/mercadopago/dx-php/pull/61

**Comment by vousys** [comment]
Joel puede tener que ver con este issue, que haciendo el search por la external reference que me devuelve la preferencia, no me devuelve nada y se que el pago está?

```
// Busco la info de la preferencia
$preference_info = MercadoPago\Preference::find_by_id($preferencia_id);

// Busco el pago que exista asociado
$filters = array(
      "external_reference" => $preference_info->external_reference
    );
$payment_info = MercadoPago\Payment::search($filters);

```                                  
Un var_export de $payment_info me da

```
array (
)

```

EJ de pago aprobado: 
External_reference: 26/1-23-faf5a9a6e55f5e69ecea3d1c6ac3bc82/MjY=

Ej de pago pendiente:
external_reference: 63/1-20-b3642ebf2bd6744a0f167a0d24baef0d/NjM=

please, no me odies!!

**Comment by joelibaceta** [comment]
@vousys tuvimos reportes sobre `external_references` complejas que eran preformateadas en el proceso de búsqueda por el API para evitar ataques XSS, por lo que quizás podrías probar con un valor sin caracteres especiales.

**Comment by vousys** [comment]
ha ok, lo cambio para las futuras. Por que otro campo podria buscar el pago entonces? porq el preference_id no es un parametro disponible

**Comment by vousys** [comment]
Aca hice otra prueba, lo cambie y deje un pago en pendiente y me arroja otro error.

#PREFERENCE ID :43987228-3a10fe4e-63a8-4058-a9bd-15c7a6584ce5 
#External_reference: e624f0bc6bd9064cb839f223f79d9467

Fatal error: Uncaught exception 'Exception' with message 'Wrong type NULL. It should be int for property installments' in /xxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php:344 Stack trace: #0 /xxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(258): MercadoPago\Entity->tryFormat(NULL, 'int', 'installments') #1 /xxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(368): MercadoPago\Entity->_setValue('installments', NULL, false) #2 /xxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(120): MercadoPago\Entity->_fillFromArray(Object(MercadoPago\Payment), Array) #3 /xxx/crons/mercadopago-ipn.php(81): MercadoPago\Entity::search(Array) #4 {main} thrown in /xxx/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php on line 344
