### ISSUE TITLE
Where is MercadoPago\Preapproval::load() ?

### ISSUE THREAD

**Issue by daviduarte** [mercadopago/dx-php#57]
In [documentation page](https://www.mercadopago.com.br/developers/pt/guides/subscriptions/web-checkout/manage-subscription):  

`<?php

  $preapproval = MercadoPago\Preapproval::load($preapproval_id);
  $preapproval->auto_recurring["transaction_amount"] =  500;
  $preapproval->update();

?>`

But in MercadoPago/Entities/Preapproval.php threre ins't a method load(), nor in MercadoPago/Entity.php, wich Preapproval.php extends. 

So, if I execute the code:

`$preapproval_id = "my approval id ;)";
$preapproval = MercadoPago\Preapproval::load($preapproval_id);

var_dump($retorno);
`
I get the error:

Fatal error: Uncaught Error: Call to undefined method MercadoPago\Preapproval::load() in /var/www/html/listening.php:15

**Comment by joelibaceta** [comment]
Sorry @daviduarte we are going to update the docs, actually the `load` method has be renamed to `find_by_id`
