### ISSUE TITLE
Usar el atributo $preapproval_plan_id

### ISSUE THREAD

**Issue by arodu** [mercadopago/dx-php#59]
Estoy tratando de usar el atributo preapproval_plan_id de la clase Preapproval, para ver si puedo asignar las subscripciones a un plan de suscripcion creado desde la interfaz web de mercadopago, al hacerlo me lanza el siguiente error

```
[
	'code' => (int) 400,
	'body' => [
		'message' => 'card_id is required',
		'error' => 'bad_request',
		'status' => (int) 400,
		'cause' => []
	]
]
```
No entiendo por que esta requiriendo el atributo card_id en este caso,

Si hay alguna otra manera de asignar una suscripcion a un plan de suscripcion me gustaria saberlo.

Gracias.

**Comment by joelibaceta** [comment]
La entidad `preapproval` representa un conjunto de parámetros para iniciar un checkout de suscripción, no representa un plan, sino una configuración para realizar un cobro recurrente el cual se inicia a partir de la url almacenada en el campo init_point.

**Comment by gabomasi** [comment]
Es posible crear una preapproval utilizando una entidad plan?
Que representa entonces el campo preapproval_plan_id?
