### ISSUE TITLE
Cupom de Desconto

### ISSUE THREAD

**Issue by yudikondo** [mercadopago/dx-php#63]
Não achei nada que informe como posso implementar o desconto no valor final vindo de um cupom de desconto. 

Existe algum método exemplo: ->setDiscount() ou como o PagSeguro oferece: ->setExtraAmount(-10);

**Comment by yudikondo** [comment]
Para o pessoal que pode ter a mesma dúvida:

`array_push($Items["items"], 
	array (
		"id" 	=> 'CUPOM-LOJA', 
		"title" => "Cupom de Desconto", 
		"quantity" => 1, 
		"unit_price" => -$discount
	)
);`

Funcionou aqui. Abraços!

**Comment by joelibaceta** [comment]
@yudikondo Você não pode definir um desconto a partir do código, é necessário criar descontos no [painel o MercadoPago](https://www.mercadopago.com.ar/settings/my-business)

**PD:** Este recurso está disponível apenas para usuários profissionais
