### ISSUE TITLE
PHP < 5.5 empty() error

### ISSUE THREAD

**Issue by carlosmelga** [mercadopago/dx-php#64]
**Describe the bug**
In versions prior to PHP 5.5 the empty() function doesn't allow to use a function result as it's explained in http://php.net/manual/en/function.empty.php
In src/MercadoPago/Config.php:109 is usint that function, and in my installation I'm geting a Fatal error due to this.

**To Reproduce**
Use a server with PHP5.5 or lower and try to use the line MercadoPago\SDK::setClientId, you will get the fatal error.

**Suggest**
Change the content of the empty function to:

```
$accessToken = $this->get('ACCESS_TOKEN');
if ($this->get('CLIENT_ID') != "" && $this->get('CLIENT_SECRET') != "" && empty($accessToken))
```

**Comment by diego-sorribas** [comment]
Hello, Which is the minimum php version compatible? Thanls!

**Comment by carlosmelga** [comment]
Hi, as PHP website says:

(PHP 4, PHP 5, PHP 7)

empty — Determine whether a variable is empty

**Comment by diego-sorribas** [comment]
I deleted the question because I ask for the package php version but is in the readme

**Comment by carlosmelga** [comment]
Hi there,

Have you got any plans to correct this issue?

Thanks.

**Comment by joelibaceta** [comment]
We will no longer support versions minor than 5.6 in the future.
