### ISSUE TITLE
Exception with message SSL certificate RestClient.php on line 178

### ISSUE THREAD

**Issue by andresmartindoria** [mercadopago/dx-php#65]
**Describe the bug**
Estoy programando en modo sandbox en mi localhost, y me tira error de SSL

**To Reproduce**
Uso CodeIgniter
require_once 'application/libraries/vendor/autoload.php';
MercadoPago\SDK::setAccessToken($this->access_token);
Probe con solo el access token

MercadoPago\SDK::setClientId($this->CLIENT_ID);
MercadoPago\SDK::setClientSecret($this->CLIENT_SECRET);
Probe con estos 2, tanto con mis datos de producción como con un vendedor de prueba

public function createPreference ( $data )
    {
        $preference = new MercadoPago\Preference();

        # Building an item
        $item = new MercadoPago\Item();
        $item->id = $data['id'];
        $item->title = $data['title'];
        $item->quantity = $data['quantity'];
        $item->currency_id = "ARS";
        $item->unit_price = $data['unit_price'];

        # Create a payer object
        $payer = new MercadoPago\Payer();
        $payer->email = $data['cliente']->email;

        # Setting preference properties
        $preference->items = array($item);
        $preference->payer = $payer;
        $preference->save(); # Save the preference and send the HTTP Request to create

        # Return the HTML code for button
        return $preference->sandbox_init_point;
    }

**Expected behavior**
Que puede ser que no lo puedo hacer funcionar en mi local? O solo funciona en un servidor?

**Server (please complete the following information):**
LocalHost

Muchas gracias
Andres

**Comment by joelibaceta** [comment]
Hola @andresmartindoria para comunicarte con el API de MercadoPago debes tener un origen seguro para superar la etapa de handshake con el servidor, puedes configurar tu servidor web para proveer un certificado valido desde localhost, el proceso difiere según el entorno de desarrollo, para Apache por ejemplo puedes añadir los certificados en la configuración.


```
<VirtualHost *:443>
    DocumentRoot "C:/Apache24/htdocs"
    ServerName localhost
    SSLEngine on
    SSLCertificateFile "C:/Apache24/conf/ssl/server.crt"
    SSLCertificateKeyFile "C:/Apache24/conf/ssl/server.key"
</VirtualHost>
```
