### ISSUE TITLE
Preapproval various bugs

### ISSUE THREAD

**Issue by AldrinSalazar** [mercadopago/dx-php#66]
**Description**
It is impossible to create a Preapproval, there are at least two bugs:
1- The back_url parameter does not recognize the .website TLD
2- Even if i am including all the requested data, there is a "Bad request" error

**Example code (PHP)**
```php
MercadoPago\SDK::setClientId(...);
MercadoPago\SDK::setClientSecret(...);

$preapproval_data = new MercadoPago\Preapproval();
$preapproval_data->payer_email = $this->email;
//Setting for example "https://mysite.website" does not work (1)
$preapproval_data->back_url = "http://google.com";
$preapproval_data->reason = substr( $this->subscription_name, 0, 127 );
$preapproval_data->external_reference =  "VIP-" . $this->subscription_id;
//Setting the required data (2)
$preapproval_data->auto_recurring = array( 
          "frecuency" => 1, 
          "frequency_type" => "months",
          "transaction_amount" => 60,
          "currency_id" => "ARS",
          "start_date" => "2018-07-29T14:58:11.778-03:00",
          "end_date" => "2018-08-29T14:58:11.778-03:00"
);
$preapproval_data->save();
```
**Expected behavior**
Get the init_point URL to let the user follow the standard flow of the API

**Current behavior**
Case 1, using any .website TLD URL, the API responds with:
`[29-Jul-2018 16:22:34 UTC] {"message":"Invalid value for back_url, must be a valid URL","error":"bad_request","status":400,"cause":[]}`

Case 2, i am correctly setting the required data, the API responds with:
`[29-Jul-2018 16:35:55 UTC] {"message":"The parameters frequency, frequency_type, transaction_amount and currency_id are required in the recurring payments scheme","error":"bad_request","status":400,"cause":[]}`

**Additional information**
PHP 7.2.0

**Comment by joelibaceta** [comment]
@AldrinSalazar back url param doesn't support TLD by now, we have a regex matching validation which prevent this.
About he point 2, You have a typo error, you should use `"frequency"` instead of `"frecuency"`
