### ISSUE TITLE
Diferences between Plan and Preapproval

### ISSUE THREAD

**Issue by daviduarte** [mercadopago/dx-php#68]
Some days ago my Preapproval application suddently stop working, showing a generic erro message. I was pursuiting a solution and I sent a message to Mercado Pago Developers support.  The reply message was: "The Preapproval API is deprecated, we are changing to a better architeture". So I was searching for another solution to receive my recurrents payment. I found the mercadopago/plan API, wich appears the same as mercadopago/preapproval API. So, what exacly is the differences between both? What API is really deprecated? 

Sorry if this is not the best place for this question, but I was unable to find a good answer in the documentation nor in the cody of the new and old API.

Regards!

**Comment by fgilio** [comment]
Is the preapproval API really deprecated? We did not receive any notification about this

**Comment by joelibaceta** [comment]
Preapproval API will be deprecated in the future for a new API for recurring payments, actually we removed the related articules from DevSite to avoid new integrations. 
By now you can use both APIs without problems, if your integrations suddenly stop working, check if you are using TLS > 1.0 in your API calls.

**Comment by fgilio** [comment]
Hi @joelibaceta , where can I find the docs for that new API?

**Comment by joelibaceta** [comment]
@fgilio the new API is not available yet, we are working on it.

**Comment by fgilio** [comment]
Oh ok
