### ISSUE TITLE
Failed to connect to api.mercadopago.com port 443

### ISSUE THREAD

**Issue by blok-0** [mercadopago/dx-php#70]
Estaba utilizando la [sdk anterior](https://github.com/mercadopago/sdk-php) y todo iba bien, podía relizar los pagos necesarios mediante el sdk y todo hasta hace unos dias que el servidor de mercado pago dejó de responder las solicitudes para crear las preferencias con el siguiente código:

`production.ERROR: exception 'MercadoPagoException' with message 'Failed to connect to api.mercadopago.com port 443: Connection refused' in /home/appcavac/maincava/vendor/mercadopago/sdk/lib/mercadopago.php:508 Stack trace: 
#0 /home/appcavac/maincava/vendor/mercadopago/sdk/lib/mercadopago.php(557): MPRestClient::exec(Array) #1 /home/appcavac/maincava/vendor/mercadopago/sdk/lib/mercadopago.php(67): MPRestClient::post(Array) #2 /home/appcavac/maincava/vendor/mercadopago/sdk/lib/mercadopago.php(210): MP->get_access_token() #3 /home/appcavac/maincava/app/Http/Controllers/ApiController.php(963): MP->create_preference(Array)`

Entonces, gracias a un usuario que me informó esta nueva sdk, decidí utilizarla pero, :open_mouth: ahh sorpresa, cuando la implemento sigue apareciendo el mismo error que me aparecía en la sdk anterior.

`production.ERROR: exception 'Exception' with message 'Failed to connect to api.mercadopago.com port 443: Connection refused' in /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/RestClient.php:178 Stack trace:
#0 /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/RestClient.php(216): MercadoPago\RestClient->exec(Array)
#1 /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/Config.php(134): MercadoPago\RestClient->post('/oauth/token', Array)
#2 /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/Config.php(110): MercadoPago\Config->getToken()
#3 /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/Config/AbstractConfig.php(87): MercadoPago\Config->set('CLIENT_SECRET', 'BLABLABLABLABLA...')
#4 /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/SDK.php(74): MercadoPago\Config\AbstractConfig->configure(Array)
#5 /home/appcavac/maincava/app/Http/Controllers/ApiController.php(852): MercadoPago\SDK::setClientSecret(' BLABLABLABLA...')`

Cualquiera pensaría que mis credenciales son incorrectas y que por eso no me da autorización para conectarme, pero lo curioso esque cuando ejecuto el mismo código de la sdk en mi `localhost` las preferencias se crean perfectamente y puedo continuar con el flujo de la compra mediante la url `init_point`. Sin modificar las credenciales.

Estoy utilizando laravel 5.2, montando en un servidor de hostingmexico.
¿Alguna idea de porque sucede esto?

Saludos!!! :raised_hand_with_fingers_splayed:

**Comment by blok-0** [comment]
Me vuelve a dar el error. Justo ayer estaba bien, y me permitia hacer los pagos. Hoy de la nada vuelve a dar el error desde mi servidor de producción.
`'Exception' with message 'Failed to connect to api.mercadopago.com port 443: Connection refused' in /home/appcavac/maincava/vendor/mercadopago/dx-php/src/MercadoPago/RestClient.php:178`
Cuando lo intento desde localhost todo va bien.

**Comment by blok-0** [comment]
[tls 1.2 ](https://www.mercadopago.com.ar/developers/en/guides/pci-compliant-merchants/disabling-tls-10)

**Comment by fgilio** [comment]
Se puede testear así:
```php
$ch = curl_init('https://www.howsmyssl.com/a/check'); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
$data = curl_exec($ch); 
curl_close($ch); 
echo json_decode($data)->tls_version;
```
Para probar desde Tinker:
```php
$ch = curl_init('https://www.howsmyssl.com/a/check'); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); $data = curl_exec($ch); curl_close($ch); echo json_decode($data)->tls_version;
```
Fuente: https://gist.github.com/olivierbellone/5fbe074004059c1be5cc81408b72c7b3
