### ISSUE TITLE
Parámetros expires y expiration_date_from

### ISSUE THREAD

**Issue by edgargrs** [mercadopago/dx-php#71]
Tengo montado un checkout básico y necesito que la preferencia expire despues de **x** tiempo.
Al momento de crear una preferencia, envio el parametro expires como `true`, y le mando en los campos `expiration_date_from` y `expiration_date_to` algo como esto.
`2018-08-22T14:17:18.000-05:00`
`2018-08-22T14:37:18.000-05:00`
En la [documentación oficial](http://beta.mercadopago.com.mx/developers/es/reference/preferences/_preferences/post/), solo explica que dichos campos deben estar bajo el formato `Date(ISO_8601) `, pero no muestra ningún ejemplo asi que me estoy basando en el ejemplo de la documentación de la [sdk anterior](https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/receive-payments/additional-info/). Antes tenía implementado el sdk anterior, y los parametros que enviavan estaban bien, pero ahora no sé si exista alguna modificación en la nueva sdk para estos campos.
Dejo las funciones que utilizo para crear la información de dichos campos.

1. 
`$mytime = Carbon\Carbon::now();`
`$inicio = date('Y-m-d\TH:i:s.000P', strtotime($mytime));`
`$fin = date('Y-m-d\TH:i:s.000P', strtotime($mytime->addMinutes(20)));`
`return ['inicio' => $inicio, 'fin' => $fin];`

2. 
`$t = microtime(true);`
`$micro = sprintf("%06d",($t - floor($t)) * 1000000);`
`$d = new DateTime( date('Y-m-d H:i:s.'.$micro, $t) );`
`$inicio = $d->format("Y-m-d\TH:i:s.uP");`
`$inicioCarbon = Carbon\Carbon::createFromFormat('Y-m-d\TH:i:s.uP', $inicio);`
`$finCarbon = Carbon\Carbon::createFromFormat('Y-m-d\TH:i:s.uP', $inicio)->addMinutes(20).".".$micro;`
`$df = new DateTime( $finCarbon );`
`$fin = $df->format("Y-m-d\TH:i:s.uP");`
`$lastInicio = substr($inicio,-6);`
`$lastFin = substr($fin,-6);`
`$inicio = substr($inicio,0,23).$lastInicio;`
`$fin = substr($fin,0,23).$lastFin;
`return ['inicio' => $inicio, 'fin' => $fin];`

Estoy usando Laravel 5.2 con ayuda de [Carbon](https://carbon.nesbot.com/docs/)

Saludos :raised_hand_with_fingers_splayed:

**Comment by joelibaceta** [comment]
Ahora puedes enviar informacion para estos campos usando un string con el formato de fecha en ISO o una instancia DateTime.

**Comment by blok-0** [comment]
😭

**Comment by blok-0** [comment]
👎

**Comment by joelibaceta** [comment]
@blok-0 lo reviso

**Comment by blok-0** [comment]
@joelibaceta  gracias!
¿Puedes abrir el error de nuevo?
Por si a alguien mas le ha pasado :sweat_smile: 
:hand:

**Comment by edgargrs** [comment]
Gracias quedó resuelto actualizando a 1.2.1 👍
