### ISSUE TITLE
Es muy malo el control y validacion de errores

### ISSUE THREAD

**Issue by gpilla** [mercadopago/dx-php#72]
Estoy trabajando y la API no te advierte de errores, directamente no devuelve error. En el caso que estoy trabajando no habia seteado correctamente los datos de autenticación, y basicamente cuando hacia el save() solo me devolvia el objeto en el mismo estado que enviaba.

La solución que considero correcta es el manejo de Exceptions para los casos de error de comunicación. Se podria agregar 3 tipos de Exception basicas (MercadoPagoConnectionException MercadoPagoBussinessException MercadoPagoAuthException)

Como opción temporal, documentar como manejar validaciones sobre las respuestas.

**Comment by edgargrs** [comment]
+1

**Comment by nicoandrade** [comment]
+1
Termina siento mejor el viejo SDK que te devolvía el JSON con la respuesta del servidor de MP

**Comment by nicolasrivadeneira** [comment]
Buenas, han encontrado alguna solucion para esto ? estoy trabajando con una nueva app y no se si usar el sdk viejo o este, ya que me sucede lo mismo, que cuando la respuesta es 400 no retorna el error

**Comment by fgilio** [comment]
Related: https://github.com/mercadopago/dx-php/issues/124

**Comment by joelibaceta** [comment]
Estamos disponibilizando en dev-master una forma de consultar los errores del api en distintos métodos, en breve estaremos publicando la nueva version con estos cambios.

Ejemplo:

```php
    if ($payment->save()) {
      echo $payment->status;
    } else {
      echo "Ups: " . $payment->error;
    }
```

**Comment by fgilio** [comment]
IMHO al encontrar un error debería levantar un excepción, que pueda luego ser catcheada por los que implementamos:
```php
try {
    $payment->save();
    echo $payment->status;
} catch (Exception $e) {
    echo "Ups: " . $payment->error;
}
```
Pero de todos modos, se agradece esta mejora.

**Comment by joelibaceta** [comment]
@fgilio para save y update tenemos 2 tipos de errores, errores recuperables que no representan necesariamente una excepción o deban interrumpir la ejecución de la aplicación, por lo general son errores de validación y posee una estructura de detalle y codigo de error independientes y hasta multiples, podes recibir 4 causas en un mismo mensaje de error, no necesariamente representable como un stacktrace de error.

Y los errores no recuperables status 500, que si, deberían romper la aplicación y deben ser controlados.
