### ISSUE TITLE
Error en calculadora de monto de envios

### ISSUE THREAD

**Issue by lsfiege** [mercadopago/dx-php#75]
En la documentación no se detalla explícitamente cómo debe realizarse la consulta a la API para obtener el valor correspondiente a los metodos de envio.

Si se intenta, por intuición, con esto:
```
$params = [
    "dimensions" => "30x30x30,500",
    "zip_code" => $customer_postcode,
    "item_price" => $price
];

$response = MercadoPago\SDK::get('/shipping_options', $params);
```
Se obtiene un error como el siguiente:
`[  
  "code" => 400  
  "body" => array:4 [  
    "message" => "Invalid dimensions"  
    "cause" => null  
    "error" => "invalid_dimensions"  
    "status" => 400  
  ]  
]
`

Podrían aclarar si esta consulta es correcta o bien, cómo debe realizarse?

**Comment by lsfiege** [comment]
@joelibaceta alguna novedad de esto?

**Comment by lsfiege** [comment]
Comento con la resolución que me brindaron vía email ya que acá no tuve respuesta.  

`MercadoPago\SDK::setClientId(env('MP_CLIENT'));`  
`MercadoPago\SDK::setClientSecret(env('MP_SECRET'));`  
  
`
$params = [
    'url_query' => [
        'dimensions' => '30x30x30,500',
        'zip_code' => $customer_postcode,
        'item_price' => $price,
        'free_method' => $free_method_id //opcional
    ]
];`    
  
`$response = MercadoPago\SDK::get('/shipping_options', $params);`

**Comment by lsfiege** [comment]
Comento con la resolución que me brindaron vía email

`MercadoPago\SDK::setClientId(env('MP_CLIENT'));`  
`MercadoPago\SDK::setClientSecret(env('MP_SECRET'));`  
  
`
$params = [
    'url_query' => [
        'dimensions' => '30x30x30,500',
        'zip_code' => $customer_postcode,
        'item_price' => $price,
        'free_method' => $free_method_id //opcional
    ]
];`    
  
`$response = MercadoPago\SDK::get('/shipping_options', $params);`

**Comment by lucaasleaal** [comment]
Same problem now, and this example gave me the same error.
Mesmo problema agora, e este exemplo me deu o mesmo erro.

> Comento con la resolución que me brindaron vía email
> 
> `MercadoPago\SDK::setClientId(env('MP_CLIENT'));`
> `MercadoPago\SDK::setClientSecret(env('MP_SECRET'));`
> 
> ` $params = [ 'url_query' => [ 'dimensions' => '30x30x30,500', 'zip_code' => $customer_postcode, 'item_price' => $price, 'free_method' => $free_method_id //opcional ] ];`
> 
> `$response = MercadoPago\SDK::get('/shipping_options', $params);`

Same problem now, and this example gave me the same error.
Mesmo problema agora, e este exemplo me deu o mesmo erro.
