### ISSUE TITLE
Marketplace y merchant_orders

### ISSUE THREAD

**Issue by esteban-turnocheck** [mercadopago/dx-php#79]
Hola @joelibaceta, hola gente. Escribí esta consulta por todos lados, y no consigo evacuarla. Intento acá, ya que este repo parece tener mucha actividad.

Estoy haciendo un marketplace, con checkout básico. Lo tengo bastante avanzado, ya puedo hacer la venta, y hasta he hecho ventas reales.

Entendí, leyendo los foros y experimentando, que en la IPN, para pedir el merchant order, tenés que ir a buscar las credenciales de tu vendedor, y no las tuyas como plataforma.

Ahora bien.

En el momento de hacer el checkout, lo que yo estoy haciendo es generar la preferencia. En el campo external_reference de la preferencia, pongo el id de mi venta, o sea el id que yo le asigno a esa venta en mi db. Y en el mismo registro de esa venta guardo el id de mi vendedor, del que haya hecho ESA venta.

Cuando el IPN, recibe una notificación con el topic=payment, voy con el id a pedir el payment_info. Como en el payment info, uno de los campos que vienen es el external_reference, con eso vuelvo a mi db, busco la venta con ese id, ahí tengo el id del vendedor, y con el id del vendedor traigo las credenciales del vendedor. Luego, me traigo el merchant_order usando esas credenciales del vendedor.

Hasta ahí perfecto.

La pregunta es: qué hago cuando en el IPN, en vez de topic=payment, me viene topic=merchant_order?ID_DE_LA_MERCHANT_ORDER? No tengo manera de relacionarlo con ningún dato que pueda tener en mi db, porque al momento de hacer la venta, obviamente no tengo el merchant_order_id, y al momento del IPN solo tengo el merchant_order_id, pero no se a qué vendedor le corresponde, y entonces no puedo ir a pedir los detalles de la merchant order con las credenciales del vendedor.

Alguien puede echarme una mano con esto? Claramente podría desactivar el IPN de merchant_orders, es una de las opciones que te da mercadopago cuando configurás la URL de notificaciones, pero no tengo claro qué pierdo si solo me quedo escuchando los pagos.

Después, incluso, me di cuenta de que en el callback de success, ahí si te viene el merchant_order_id. Es medio pasito adelante, pero vamos dos para atrás, porque podría ser que el comprador nunca llegara al callback de success (si termina de pagar y cierra el browser, por ejemplo)

Lo que entiendo que sucede dejando de recibir las merchant_order en el IPN son dos cosas: la primera es que siempre se te escapa la primer merchant order, que es la que te indica que arrancó un proceso de compra (o sea que tu comprador le dio al botón de checkout), porque te llega antes el IPN con el payment. Eso podría no ser tan grave. Pero la segunda cosa que sucede, es que te perdés todas la merchant_order de todos los eventos que no pasen por tu app, sino directamente desde la página de MP. Si el comprador, por ejemplo, se loguea en su cuenta y cancela el pago, o hace un litigio (si da de baja su cuenta de MP!) nunca te enterás porque solo estás escuchando los payment en tu IPN.

En definitiva, puede ser que me esté perdiendo de algo, o puede ser que no terminé de entender qué es una merchant_order, y si toda la info que necesitamos para procesar un pago y llevar registro de lo que está pasando con esa compra, la tengo igual escuchando solamente el topic=payment. Y en tal caso, para qué existe el topic=merchant_order?

Help!!! Alguien?
Saludos!

**Comment by mcontartesi** [comment]
Nunca nos funcionan bien las notificaciones en nuestra practica. Lo ideal es con el numero interno ir a buscarlo a MP.

**Comment by esteban-turnocheck** [comment]
Hola Maximiliano. Gracias por contestar! Es una brahma helada en pleno desierto tu respuesta. Jajaja!
No entiendo exactamente a qué te referís con el número interno, o de dónde lo podemos sacar. Pero entiendo que lo que vos me estás recomendando, es olvidarme de las IPN (o sea, el script del IPN que siempre devuelva un 200) y pedir con un cron o algo así los datos a MP. Es así? Si podés, aclarame eso un cachito. Y entonces, qué son o para qué están las notificaciones de tipo topic=merchant_order?
Gracias viejo!

**Comment by mcontartesi** [comment]
Jajaj! Sí! Lamentablemente la documentacion sigue siendo mala pese al esfuerzo del team de MP. 
Fijate si podes enviar este campo, donde le pones una referencia tuya y luego preguntas el status del pago por referencia del external:

"external_reference": "Order_1234",

Eso lo podes hacer en forma sincronica, al momento de que Mercadopago te devuelve el usuario a la url definida o por un CRON. Tambine lo podrias hacer desde un javascript dentro de un iframe.

Tambien proba con los Webhooks a ver si te da resultado, (en mi caso la experiencia tambien es mala, si bien no tengo recuerdo exacto con que renegue, no funciona tan bien los hooks como los de MELI)

https://www.mercadopago.com/mla/account/webhooks

Abz!

**Comment by esteban-turnocheck** [comment]
No sabía que podía hacer un find del payment por el campo external_reference que, de hecho, lo estoy usando tal como decís.
Mañana me dedico a probar eso y posteo los hallazgos.
De nuevo: gracias!!

**Comment by fdiaz7** [comment]
Hola, yo estoy en la misma. 
Probando me di cuenta que en las url success devuelven una variable get que es collection_id, esa variable coincide con el payment_id.
Así que hago las consultas a partir de ese dato. Sin usar las IPN

**Comment by esteban-turnocheck** [comment]
Hola @fdiaz7 . Primero, como le decía a @mcontartesi , gracias por participar. Es muy difícil conseguir información en estos temas.
Si, es verdad lo que decís, pero yo entiendo que uno no puede contar con que el usuario termine siempre en la url success. El tipo puede terminar de comprar en MP, y cerrar el browser. Entonces nunca va a parar a la url success. De hecho, si uno pudiese estar seguro de eso, yo no tendría tampoco el problema que planteo (que es que desconozco las credenciales necesarias para ir a buscar el merchant_order cuando viene una IPN con topic=merchant_order.
Ahora, con la gran sugerencia que nos aporta @mcontartesi , si que se puede ir a buscar el payment. Es decir, con el external_reference, que es el ID con el que vos te guardás la venta en la db. Hoy ni bien arranqué me fui a fijar en la docu, y el endpoint /v1/payments/search, te permite buscar por external_reference, y de ahí te traés el pago, y del pago te traés la merchant_order con las credenciales de tu vendedor (siempre aclarando que mi problema en particular se da porque estoy usando marketplace, ojo)
Y eso, como dice @mcontartesi , lo podés hacer tanto desde la url success como con un cronjob, en caso de que el usuario no haya terminado en la url success, como decía antes.
Todavía no probé nada de esto, lo voy a hacer hoy (si la vida me deja laburar en paz! jajaja) y después comento. 
Mientras, obvio, son bienvenidas las ideas.
Gracias, de nuevo, a ambos.

**Comment by fdiaz7** [comment]
Mmmmm verdad. 
Bueno voy a intentar los mismo y después te cuento cómo fue jaja.

**Comment by joelibaceta** [comment]
@esteban-turnocheck este canal esta dedicado al reporte de bugs o generar discusión sobre sugerencias o aportes sobre este SDK en particular, voy a cerrar este hilo.

**Comment by fgilio** [comment]
@joelibaceta dónde se pueden continuar estas charlas? Son muy valiosas

**Comment by joelibaceta** [comment]
@fgilio para discusiones entre usuarios de la comunidad de desarrolladores dejamos activo el foro de desarrolladores [](https://www.mercadopago.com.ar/developers/es/community/forum/).

**Comment by fgilio** [comment]
Es un garrón el foro, espero puedan ofrecer algo mejor pronto.
