### ISSUE TITLE
Customer update y delete no funcionan

### ISSUE THREAD

**Issue by lostlian** [mercadopago/dx-php#80]
**Descripción**
Customer Update siempre falla. y Customer delete no esta implementado

**Ejemplo para reproducir**

```
$customer = new \MercadoPago\Customer();
$customer->id = $user->customerId;
$params = [
	'email' => $user->email,
	'first_name'=> $user->first_name,
	'last_name'	=> $user->last_name,
];
$customer->update($params)
```

y así

```
$customer = new \MercadoPago\Customer();
$customer->id = $user->customerId;
$customer->email = $user->email;
$customer->first_name = $user->first_name;	
$customer->last_name = $user->last_name;
$customer->update()
```
Ambas generan el mismo error.

`Trying to get property 'id' of non-object`
El error se da en la linea 266 de la clase Manager

Creo que el error esta en el método `_deltaToJson` pero no entiendo su razón de ser.

**Comment by lostlian** [comment]
Tuve que cambiar en la clase manager de la línea 265 a 270

de esto
```
$last = $entity->_last;
$last_value = $last->$key;
if ($last_value != $value){
        $result[$key] = $value;
}
```

a esto

```
$result[$key] = $value;
```

Con esto funcionó correctamente.

**Comment by joelibaceta** [comment]
@lostlian  voy a revisarlo, gracias por reportarlo.

**Comment by joelibaceta** [comment]
@lostlian el update ya debería estar andando.
