### ISSUE TITLE
Parse error: syntax error, unexpected '[', expecting ')'

### ISSUE THREAD

**Issue by santosandreluiz** [mercadopago/dx-php#82]
I'm having problem with file below:
Parse error: syntax error, unexpected '[', expecting ')' in /vendor/mercadopago/dx-php/src/MercadoPago/SDK.php on line 45

I'm using PHP 5.3.29.

What could be this issue?

**Comment by joelibaceta** [comment]
@santosandreluiz which SDK version are you using?

**Comment by joelibaceta** [comment]
@santosandreluiz PHP 5.3 is not supported, we are using features not supported in versions previous than 5.4.
