### ISSUE TITLE
Problema con respuesta

### ISSUE THREAD

**Issue by elinsoluble** [mercadopago/dx-php#83]
Hola, tengo un problema con la respuesta cuando consulto por las credenciales de un usuario.

Segun la documentacion me tendria que devolver un json, pero cuando quiero empezar a usar la informacion, no pedo, porqeuu la respuesta esta un el formato string.

Yo nose si a partir de ahi tengo que hacer algo mas para poder obtener los datos.

Aclaro que recien estoy empezando a usar el sdk de mercado pago, asi que cualqueir aclaracion estare agradecido.

La version del sdk que estoy usando es 1.0.0

**Comment by joelibaceta** [comment]
Hola @elinsoluble veo varios posibles problemas aquí:

- Estas usando una version del SDK anticuada, la ultima es 1.1.7
- Para esta versión del SDK las credenciales son configuradas en el primer momento y posteriormente se consultara por el access_token de forma automática antes de realizar un request.
- Estas siguiendo una documentación de una version anterior a la 1.0.0 del SDK.
