### ISSUE TITLE
No se puede cancelar un Payment

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#88]
**Describe the bug**
"mercadopago/dx-php": "dev-master"
Ya no puedo cancelar un payment in process.

**To Reproduce**
Probé de 2 maneras:

1)
```php
$payment = Payment::find_by_id($id); // Recupera un payment con status "in_process" => funciona.
$payment->status = 'cancelled';
$payment->save();
$payment = Payment::find_by_id($id); // El payment todavía tiene el status "in_process".
```
2)
```php
$payment = Payment::find_by_id($id); // Recupera un payment con status "in_process" => funciona.
$payment->status = 'cancelled';
$payment->update(); // Dispara una Exception "Undefined index: date_last_updated".
```

**Expected behavior**
Corregir o indicarme una manera de poder cancelar un payment :)

**Screenshots**
N/A

**Server (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by joelibaceta** [comment]
hola @nitescent , gracias por el reporte, la manera correcta seria:

```php
$payment = Payment::find_by_id($id); // Recupera un payment con status "in_process" => funciona.
$payment->status = 'cancelled';
$payment->update();
```

Vamos a revisar si esto esta funcionando correctamente.

**Comment by nitescent** [comment]
Hola @joelibaceta !
Ok espero tu respuesta.
Hasta ahora siempre pude cancelar pago con status "in_process". Ha cambiado la regla?

**Comment by joelibaceta** [comment]
Es correcto, `in_process`, `pending` son estados intermedios los cuales pueden ser cancelados, los estados finales como canceled o approved o rejected no pueden ser cancelados

**Comment by nitescent** [comment]
Ok gracias entonces estoy haciendo las cosas bien. Espero su respuesta, porque por ahora no funciona el update del status a 'canceled'.

**Comment by lsfiege** [comment]
Me sumo a lo reportado por @nitescent, no funciona la cancelación, y al tratar de obtener el `Payment` vía `Payment::find_by_id($id);` devuelve un objeto `Payment` con todas las propiedades en `null`

**Comment by nitescent** [comment]
Hola, recién probé de nuevo haciendo

```
$payment = Payment::find_by_id($id); // Recupera un payment con status "in_process" => funciona.
$payment->status = 'cancelled';
$payment->update();
```

Y de nuevo `$payment->update();` disparó una Exception "Undefined index: date_last_updated".

Pero el payment quedó en el status cancelled.

Está en parte resuelto @joelibaceta

**Comment by joelibaceta** [comment]
@nitescent  estamos trabajando en corregir esto.

**Comment by joelibaceta** [comment]
@nitescent Esta resuelto en la versión 1.1.9, también reportamos un posible bug interno sobre pagos en estado `in_process` que después de cancelarse correctamente se mantienen en ese estado.

**Comment by lsfiege** [comment]
En mi caso, luego de actualizar el componente, sigue sin funcionar la cancelación de un pago con estado "cobro pendiente"

**Comment by nitescent** [comment]
> 1.1.9

Hola @joelibaceta, había entendido que teníamos que utilizar dev-master.
Debo utilizar 1.1.9 entonces?

**Comment by nitescent** [comment]
> @nitescent Esta resuelto en la versión **1.1.9**, también reportamos un posible bug interno sobre pagos en estado `in_process` que después de cancelarse correctamente se mantienen en ese estado.

Hola @joelibaceta, había entendido que teníamos que utilizar dev-master.
Debo utilizar 1.1.9 entonces?

**Comment by joelibaceta** [comment]
@nitescent para este caso es lo mismo, mencione 1.1.9 como marcador de temporalidad para identificar cuando se introdujo este fix.

**Comment by lsfiege** [comment]
@joelibaceta consulta, para que esto funcione, se debe usar access token o client id + secret? Lo pregunto porque en la documentación no está aclarado y es un poco confuso

**Comment by joelibaceta** [comment]
@lsfiege Access Token, adicionalmente te dejo el repo de la documentación para que puedas dejar tu sugerencia https://github.com/mercadopago/devsite-docs

**Comment by lsfiege** [comment]
gracias!

**Comment by lsfiege** [comment]
> @lsfiege Access Token, adicionalmente te dejo el repo de la documentación para que puedas dejar tu sugerencia https://github.com/mercadopago/devsite-docs

gracias!
