### ISSUE TITLE
Se hizo refund de un Payment de PROD con el token de TEST

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#89]
**Describe the bug**
Hola, abrí un ticket https://www.mercadopago.com.ar/developers/es/support el 30 de octubre y nunca tuve respuesta.
Había un bug en la API y generó un error grave.
En entorno de test con el token de TEST pude hacer refund de un Payment de PROD.
Ahora constato que ya no es posible: el get payment con el token de TEST me retorna 404 NOT FOUND.
Yo había guardado el resultado del CURL el 30 de octubre: [out.txt](https://github.com/mercadopago/dx-php/files/2600240/out.txt)

Ahora el bug parece resuelto.
Pero qué hacemos con el dinero perdido? Me lo reintegran?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Server (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by joelibaceta** [comment]
@nitescent este canal esta destinado únicamente a la discusión sobre incidencias, bugs o consultas sobre el SDK que aloja este repositorio, para consultas genéricas sobre Mercado Pago o una integración, puedes usar el canal oficial de soporte http://mercadopago.com.ar/developers/es/support

Procedo a cerrar el issue

**Comment by nitescent** [comment]
Hola @joelibaceta 
Pensaba que poder ver/modificar los Payments de PROD con el token de TEST era un bug del SDK.
No quiero molestar pero nunca tuve una respuesta de http://mercadopago.com.ar/developers/es/support desde hace 3 semanas, cómo puedo hacer?

**Comment by joelibaceta** [comment]
@nitescent el SDK mantiene un único `access_token` para simplificar el proceso y que todas las llamadas sean consistentes, una vez definido, este se usa a lo largo de la aplicación.
