### ISSUE TITLE
Failing pipelines

### ISSUE THREAD

**Issue by ahoulgrave** [mercadopago/dx-php#93]
**Describe the bug**
Pipelines are not passing

**To Reproduce**
Go to https://travis-ci.org/mercadopago/dx-php and see it for yourself

**Expected behavior**
Pipelines passing

**Screenshots**
![builds mercadopago dx php travis ci](https://user-images.githubusercontent.com/3420583/48969748-62ebf880-f003-11e8-9db1-f0a77769d7a6.png)

Last successfull build: **2 years ago**

**Server (please complete the following information):**
TravisCI servers

**Additional context**
Need to fix as it's the official SDK

**Comment by joelibaceta** [comment]
@ahoulgrave we are working to update our test suites.

**Comment by ahoulgrave** [comment]
Thanks @joelibaceta 

Currently you have dev dependencies (https://github.com/mercadopago/dx-php/blob/90846e51fff6f59214555b5c77f8f54876e76a50/composer.json#L24) that requires php 7.1 https://packagist.org/packages/phpunit/phpunit#7.2.7

so the pipelines will never pass unless you require this same version

**Comment by joelibaceta** [comment]
@ahoulgrave we changed this to `"phpunit/phpunit": "^5",`

**Comment by ahoulgrave** [comment]
Still a lot of errors, i will make a PR when i have time

**Comment by fgilio** [comment]
.travis.yml is targeting PHP 5.3 and 5.5, those should be removed and 7.1, 7.2 and 7.3 added.
I'd make a PR with this tiny changes but I guess @ahoulgrave is going to include it already in his PR. Otherwise, I'd happy to make it.

**Comment by ahoulgrave** [comment]
According to [the readme](https://github.com/mercadopago/dx-php/blob/0e2967e907829913aab5c1ebd34af399e5ee695e/README.md#php-versions-supported):
```
The SDK supports PHP 5.6 or major
```

Also check https://github.com/mercadopago/dx-php/blob/0e2967e907829913aab5c1ebd34af399e5ee695e/composer.json#L24

According to readme, php 5.5 is not supported, you'll get an error installing dependencies under php 5.5

So the pipelines should work at least for all versions >= 5.6

**Comment by ahoulgrave** [comment]
Also, the output from phpunit 5 is:
```
....E.E.E..EFF.E.E....ERRRR.ERRRREIIIIIII
```

So lots of errors to fix

**Comment by ahoulgrave** [comment]
@joelibaceta Can you create a PR please?

**Comment by joelibaceta** [comment]
https://github.com/mercadopago/dx-php/pull/114

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-php/pull/114

**Comment by ahoulgrave** [comment]
@joelibaceta thanks!
