### ISSUE TITLE
Tipado de atributos de Preference envía fechas con formato inválido

### ISSUE THREAD

**Issue by Agusfn** [mercadopago/dx-php#94]
Los atributos expiration_date_from y expiration_date_to de MercadoPago\Preference tienen un tipado "date" que al asignarle una fecha a estos atributos, esta se convierte a este formato: ej: 2018-11-26T16:35:40-0500
El problema es que la API pide un formato con milisegundos, ej: 2018-11-26T16:35:40.123-0500 

Es decir que, al menos para mí, cuando quise utilizar el sdk y establecer fechas de expiración de la preferencia, devuelve error.

**Comment by joelibaceta** [comment]
Gracias por la observación, revisaremos el formato de fechas.

**Comment by Agusfn** [comment]
No problem

**Comment by joelibaceta** [comment]
@Agusfn Al parecer hay un bug histórico sobre formatos ISO 8601 con milisegundos, vamos a tratar de corregir eso o buscar un workaround.

**Comment by joelibaceta** [comment]
@Agusfn  solved in https://github.com/mercadopago/dx-php/releases/tag/1.2.0

**Comment by edgargrs** [comment]
#71
