### ISSUE TITLE
Installment y Subscription

### ISSUE THREAD

**Issue by nitescent** [mercadopago/dx-php#95]
Es posible ofrecer cuotas (installments) para el pago recurrente de una suscripción?

Cuando el usuario pone los datos de su tarjeta, entiendo que podría seleccionar las cuotas en el form de la tarjeta de crédito y así se genera la suscripción. Pero para los pagos automáticos siguientes cómo funcionaría?

**Comment by joelibaceta** [comment]
@nitescent te recuerdo que este canal esta destinado para reporte de errores o problemas con el SDK de MercadoPago, para consultas generales sobre la operación con MercadoPago y otros productos te dejo el canal de soporte oficial https://www.mercadopago.com.ar/developers/es/support

**Comment by nitescent** [comment]
@joelibaceta ok. Este canal no me responde NUNCA después de varias semanas. Qué me recomendás hacer?

**Comment by joelibaceta** [comment]
@nitescent recomiendo mantener el orden de los canales para organizar mejor las discusiones y diferenciarlo del soporte a usuarios el cual no es el fin de este canal, paso a cerrar el issue.
